In [1]:
import pandas as pd
import numpy as np

import lightgbm as lgb
import xgboost as xgb
from catboost import CatBoostClassifier

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score

print("LightGBM:", lgb.__version__)
print("XGBoost:", xgb.__version__)

LightGBM: 4.7.0
XGBoost: 3.4.1

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
sample_submission = pd.read_csv("sample_submission.csv")

print("Train:", train.shape)
print("Test:", test.shape)
print("Sample:", sample_submission.shape)

Train: (691369, 14)
Test: (296302, 13)
Sample: (296302, 2)

In [3]:
y = train["addicted_label"]

X = train.drop(
    columns=["addicted_label", "id"]
)

X_test = test.drop(
    columns=["id"]
)

print("X:", X.shape)
print("y:", y.shape)
print("X_test:", X_test.shape)

X: (691369, 12)
y: (691369,)
X_test: (296302, 12)

In [4]:
categorical_columns = X.select_dtypes(
    include=["object", "category"]
).columns.tolist()

print("Categorical columns:")
print(categorical_columns)

Categorical columns:
['gender', 'stress_level', 'academic_work_impact']

C:\Users\ASUS\AppData\Local\Temp\ipykernel_16592\986657640.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X.select_dtypes(

In [5]:
for col in categorical_columns:
    X[col] = X[col].astype("category")
    X_test[col] = X_test[col].astype("category")

In [6]:
skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

folds = list(
    skf.split(X, y)
)

print("Number of folds:", len(folds))

Number of folds: 5

In [7]:
lgb_oof = np.zeros(len(X))
xgb_oof = np.zeros(len(X))
cat_oof = np.zeros(len(X))

lgb_test = np.zeros(len(X_test))
xgb_test = np.zeros(len(X_test))
cat_test = np.zeros(len(X_test))

In [8]:
lgb_params = {
    "objective": "binary",
    "metric": "auc",
    "boosting_type": "gbdt",

    "n_estimators": 5000,
    "learning_rate": 0.03,

    "num_leaves": 63,
    "max_depth": -1,

    "min_child_samples": 30,

    "subsample": 0.85,
    "colsample_bytree": 0.85,

    "reg_alpha": 0.1,
    "reg_lambda": 1.0,

    "random_state": 42,

    "n_jobs": -1,
    "verbosity": -1
}

In [9]:
xgb_params = {
    "objective": "binary:logistic",
    "eval_metric": "auc",

    "n_estimators": 5000,
    "learning_rate": 0.03,

    "max_depth": 8,
    "min_child_weight": 5,

    "subsample": 0.85,
    "colsample_bytree": 0.85,

    "reg_alpha": 0.1,
    "reg_lambda": 1.0,

    "tree_method": "hist",

    "random_state": 42,

    "n_jobs": -1
}

In [10]:
cat_params = {
    "loss_function": "Logloss",
    "eval_metric": "AUC",

    "iterations": 5000,
    "learning_rate": 0.03,

    "depth": 8,

    "l2_leaf_reg": 5,

    "random_seed": 42,

    "verbose": 100,

    "thread_count": -1,

    "allow_writing_files": False
}

In [11]:
cat_feature_indices = [
    X.columns.get_loc(col)
    for col in categorical_columns
]

print(cat_feature_indices)

[9, 10, 11]

In [12]:
X_cat = X.copy()
X_test_cat = X_test.copy()

In [14]:
X_cat = X.copy()
X_test_cat = X_test.copy()

for col in categorical_columns:
    X_cat[col] = X_cat[col].astype("object")
    X_test_cat[col] = X_test_cat[col].astype("object")

    X_cat[col] = X_cat[col].fillna("__MISSING__")
    X_test_cat[col] = X_test_cat[col].fillna("__MISSING__")

    X_cat[col] = X_cat[col].astype(str)
    X_test_cat[col] = X_test_cat[col].astype(str)

In [15]:
X_xgb = X.copy()
X_test_xgb = X_test.copy()

for col in categorical_columns:

    combined = pd.concat(
        [
            X_xgb[col],
            X_test_xgb[col]
        ],
        axis=0
    ).astype(str)

    categories = pd.Categorical(
        combined
    ).categories

    X_xgb[col] = pd.Categorical(
        X_xgb[col].astype(str),
        categories=categories
    ).codes

    X_test_xgb[col] = pd.Categorical(
        X_test_xgb[col].astype(str),
        categories=categories
    ).codes

In [16]:
cat_feature_indices = [
    X_cat.columns.get_loc(col)
    for col in categorical_columns
]

print(cat_feature_indices)

[9, 10, 11]

In [17]:
for col in categorical_columns:
    print(
        col,
        "missing:",
        X_cat[col].isna().sum()
    )

gender missing: 0
stress_level missing: 0
academic_work_impact missing: 0

In [22]:
for fold, (train_idx, valid_idx) in enumerate(folds, 1):

    print("\n")
    print("=" * 70)
    print(f"FOLD {fold}/5")
    print("=" * 70)


    # ========================================================
    # LIGHTGBM DATA
    # ========================================================

    X_train_lgb = X.iloc[train_idx]
    X_valid_lgb = X.iloc[valid_idx]

    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]


    # ========================================================
    # XGBOOST DATA
    # ========================================================

    X_train_xgb = X_xgb.iloc[train_idx]
    X_valid_xgb = X_xgb.iloc[valid_idx]


    # ========================================================
    # CATBOOST DATA
    # ========================================================

    X_train_cat = X_cat.iloc[train_idx]
    X_valid_cat = X_cat.iloc[valid_idx]


    # ========================================================
    # LIGHTGBM
    # ========================================================

    print("\n----- LIGHTGBM -----")

    lgb_model = lgb.LGBMClassifier(
        **lgb_params
    )

    lgb_model.fit(
        X_train_lgb,
        y_train,

        eval_set=[
            (X_valid_lgb, y_valid)
        ],

        eval_metric="auc",

        categorical_feature=categorical_columns,

        callbacks=[
            lgb.early_stopping(
                stopping_rounds=200,
                verbose=True
            ),
            lgb.log_evaluation(
                period=100
            )
        ]
    )

    lgb_valid_pred = lgb_model.predict_proba(
        X_valid_lgb
    )[:, 1]

    lgb_test_pred = lgb_model.predict_proba(
        X_test
    )[:, 1]

    lgb_oof[valid_idx] = lgb_valid_pred

    lgb_test += (
        lgb_test_pred / len(folds)
    )

    print(
        f"LightGBM Fold {fold} AUC: "
        f"{roc_auc_score(y_valid, lgb_valid_pred):.6f}"
    )


    # ========================================================
    # XGBOOST
    # ========================================================

    print("\n----- XGBOOST -----")

    xgb_model = xgb.XGBClassifier(
        **xgb_params
    )

    xgb_model.fit(
        X_train_xgb,
        y_train,

        eval_set=[
            (X_valid_xgb, y_valid)
        ],

        verbose=100
    )

    xgb_valid_pred = xgb_model.predict_proba(
        X_valid_xgb
    )[:, 1]

    xgb_test_pred = xgb_model.predict_proba(
        X_test_xgb
    )[:, 1]

    xgb_oof[valid_idx] = xgb_valid_pred

    xgb_test += (
        xgb_test_pred / len(folds)
    )

    print(
        f"XGBoost Fold {fold} AUC: "
        f"{roc_auc_score(y_valid, xgb_valid_pred):.6f}"
    )


    # ========================================================
    # CATBOOST
    # ========================================================

    print("\n----- CATBOOST -----")

    cat_model = CatBoostClassifier(
        **cat_params
    )

    cat_model.fit(
        X_train_cat,
        y_train,

        eval_set=(
            X_valid_cat,
            y_valid
        ),

        cat_features=cat_feature_indices,

        early_stopping_rounds=200
    )

    cat_valid_pred = cat_model.predict_proba(
        X_valid_cat
    )[:, 1]

    cat_test_pred = cat_model.predict_proba(
        X_test_cat
    )[:, 1]

    cat_oof[valid_idx] = cat_valid_pred

    cat_test += (
        cat_test_pred / len(folds)
    )

    print(
        f"CatBoost Fold {fold} AUC: "
        f"{roc_auc_score(y_valid, cat_valid_pred):.6f}"
    )

======================================================================
FOLD 1/5
======================================================================

----- LIGHTGBM -----

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.94341
[200]	valid_0's auc: 0.954096
[300]	valid_0's auc: 0.957729
[400]	valid_0's auc: 0.959561
[500]	valid_0's auc: 0.960279
[600]	valid_0's auc: 0.960753
[700]	valid_0's auc: 0.961128
[800]	valid_0's auc: 0.961382
[900]	valid_0's auc: 0.961604
[1000]	valid_0's auc: 0.961776
[1100]	valid_0's auc: 0.961944
[1200]	valid_0's auc: 0.962124
[1300]	valid_0's auc: 0.96221
[1400]	valid_0's auc: 0.962314
[1500]	valid_0's auc: 0.962384
[1600]	valid_0's auc: 0.962458
[1700]	valid_0's auc: 0.962495
[1800]	valid_0's auc: 0.962522
[1900]	valid_0's auc: 0.962561
[2000]	valid_0's auc: 0.962602
[2100]	valid_0's auc: 0.962615
[2200]	valid_0's auc: 0.962622
[2300]	valid_0's auc: 0.962636
[2400]	valid_0's auc: 0.96266
[2500]	valid_0's auc: 0.962684
[2600]	valid_0's auc: 0.962701
[2700]	valid_0's auc: 0.962703
[2800]	valid_0's auc: 0.962722
[2900]	valid_0's auc: 0.962733
[3000]	valid_0's auc: 0.962744
[3100]	valid_0's auc: 0.962759
[3200]	valid_0's auc: 0.962794
[3300]	valid_0's auc: 0.962806
[3400]	valid_0's auc: 0.962801
[3500]	valid_0's auc: 0.9628
Early stopping, best iteration is:
[3353]	valid_0's auc: 0.962808
LightGBM Fold 1 AUC: 0.962808

----- XGBOOST -----
[0]	validation_0-auc:0.89541
[100]	validation_0-auc:0.94035
[200]	validation_0-auc:0.94760
[300]	validation_0-auc:0.95321
[400]	validation_0-auc:0.95639
[500]	validation_0-auc:0.95825
[600]	validation_0-auc:0.95977
[700]	validation_0-auc:0.96069
[800]	validation_0-auc:0.96129
[900]	validation_0-auc:0.96180
[1000]	validation_0-auc:0.96217
[1100]	validation_0-auc:0.96248
[1200]	validation_0-auc:0.96273
[1300]	validation_0-auc:0.96290
[1400]	validation_0-auc:0.96305
[1500]	validation_0-auc:0.96318
[1600]	validation_0-auc:0.96328
[1700]	validation_0-auc:0.96336
[1800]	validation_0-auc:0.96342
[1900]	validation_0-auc:0.96346
[2000]	validation_0-auc:0.96348
[2100]	validation_0-auc:0.96350
[2200]	validation_0-auc:0.96351
[2300]	validation_0-auc:0.96352
[2400]	validation_0-auc:0.96354
[2500]	validation_0-auc:0.96354
[2600]	validation_0-auc:0.96354
[2700]	validation_0-auc:0.96353
[2800]	validation_0-auc:0.96352
[2900]	validation_0-auc:0.96351
[3000]	validation_0-auc:0.96350
[3100]	validation_0-auc:0.96348
[3200]	validation_0-auc:0.96347
[3300]	validation_0-auc:0.96345
[3400]	validation_0-auc:0.96344
[3500]	validation_0-auc:0.96343
[3600]	validation_0-auc:0.96340
[3700]	validation_0-auc:0.96337
[3800]	validation_0-auc:0.96334
[3900]	validation_0-auc:0.96332
[4000]	validation_0-auc:0.96331
[4100]	validation_0-auc:0.96328
[4200]	validation_0-auc:0.96325
[4300]	validation_0-auc:0.96322
[4400]	validation_0-auc:0.96319
[4500]	validation_0-auc:0.96316
[4600]	validation_0-auc:0.96314
[4700]	validation_0-auc:0.96311
[4800]	validation_0-auc:0.96308
[4900]	validation_0-auc:0.96304
[4999]	validation_0-auc:0.96302
XGBoost Fold 1 AUC: 0.963019

----- CATBOOST -----
0:	test: 0.9120252	best: 0.9120252 (0)	total: 185ms	remaining: 15m 22s
100:	test: 0.9343048	best: 0.9343048 (100)	total: 18.2s	remaining: 14m 42s
200:	test: 0.9401034	best: 0.9401034 (200)	total: 36.1s	remaining: 14m 21s
300:	test: 0.9438545	best: 0.9438545 (300)	total: 53.8s	remaining: 13m 59s
400:	test: 0.9466748	best: 0.9466748 (400)	total: 1m 11s	remaining: 13m 38s
500:	test: 0.9491094	best: 0.9491094 (500)	total: 1m 28s	remaining: 13m 18s
600:	test: 0.9510513	best: 0.9510513 (600)	total: 1m 46s	remaining: 12m 57s
700:	test: 0.9526585	best: 0.9526585 (700)	total: 2m 4s	remaining: 12m 40s
800:	test: 0.9538792	best: 0.9538792 (800)	total: 2m 21s	remaining: 12m 24s
900:	test: 0.9549278	best: 0.9549278 (900)	total: 2m 39s	remaining: 12m 5s
1000:	test: 0.9558690	best: 0.9558690 (1000)	total: 2m 57s	remaining: 11m 47s
1100:	test: 0.9565912	best: 0.9565912 (1100)	total: 3m 14s	remaining: 11m 29s
1200:	test: 0.9571814	best: 0.9571814 (1200)	total: 3m 32s	remaining: 11m 11s
1300:	test: 0.9577017	best: 0.9577017 (1300)	total: 3m 49s	remaining: 10m 52s
1400:	test: 0.9581979	best: 0.9581979 (1400)	total: 4m 7s	remaining: 10m 34s
1500:	test: 0.9586009	best: 0.9586009 (1500)	total: 4m 24s	remaining: 10m 17s
1600:	test: 0.9589707	best: 0.9589707 (1600)	total: 4m 42s	remaining: 9m 59s
1700:	test: 0.9592768	best: 0.9592768 (1700)	total: 4m 59s	remaining: 9m 41s
1800:	test: 0.9595890	best: 0.9595890 (1800)	total: 5m 17s	remaining: 9m 23s
1900:	test: 0.9598836	best: 0.9598836 (1900)	total: 5m 35s	remaining: 9m 6s
2000:	test: 0.9601282	best: 0.9601282 (2000)	total: 5m 52s	remaining: 8m 48s
2100:	test: 0.9603695	best: 0.9603695 (2100)	total: 6m 10s	remaining: 8m 31s
2200:	test: 0.9605681	best: 0.9605681 (2200)	total: 6m 28s	remaining: 8m 13s
2300:	test: 0.9607779	best: 0.9607779 (2300)	total: 6m 46s	remaining: 7m 56s
2400:	test: 0.9609124	best: 0.9609130 (2399)	total: 7m 5s	remaining: 7m 40s
2500:	test: 0.9610849	best: 0.9610849 (2500)	total: 7m 24s	remaining: 7m 24s
2600:	test: 0.9612568	best: 0.9612568 (2600)	total: 7m 43s	remaining: 7m 7s
2700:	test: 0.9614037	best: 0.9614041 (2699)	total: 8m 2s	remaining: 6m 50s
2800:	test: 0.9615381	best: 0.9615381 (2800)	total: 8m 21s	remaining: 6m 33s
2900:	test: 0.9616582	best: 0.9616582 (2900)	total: 8m 40s	remaining: 6m 16s
3000:	test: 0.9617578	best: 0.9617578 (3000)	total: 8m 59s	remaining: 5m 59s
3100:	test: 0.9618541	best: 0.9618541 (3100)	total: 9m 18s	remaining: 5m 41s
3200:	test: 0.9619681	best: 0.9619681 (3200)	total: 9m 37s	remaining: 5m 24s
3300:	test: 0.9620458	best: 0.9620458 (3299)	total: 9m 55s	remaining: 5m 6s
3400:	test: 0.9621182	best: 0.9621182 (3400)	total: 10m 14s	remaining: 4m 48s
3500:	test: 0.9621725	best: 0.9621725 (3500)	total: 10m 33s	remaining: 4m 31s
3600:	test: 0.9622434	best: 0.9622434 (3600)	total: 10m 52s	remaining: 4m 13s
3700:	test: 0.9623004	best: 0.9623004 (3700)	total: 11m 10s	remaining: 3m 55s
3800:	test: 0.9623615	best: 0.9623624 (3796)	total: 11m 29s	remaining: 3m 37s
3900:	test: 0.9624214	best: 0.9624214 (3900)	total: 11m 48s	remaining: 3m 19s
4000:	test: 0.9624652	best: 0.9624652 (4000)	total: 12m 6s	remaining: 3m 1s
4100:	test: 0.9625031	best: 0.9625031 (4100)	total: 12m 25s	remaining: 2m 43s
4200:	test: 0.9625512	best: 0.9625514 (4199)	total: 12m 44s	remaining: 2m 25s
4300:	test: 0.9625962	best: 0.9625962 (4300)	total: 13m 2s	remaining: 2m 7s
4400:	test: 0.9626202	best: 0.9626203 (4399)	total: 13m 21s	remaining: 1m 49s
4500:	test: 0.9626535	best: 0.9626536 (4498)	total: 13m 39s	remaining: 1m 30s
4600:	test: 0.9626731	best: 0.9626738 (4599)	total: 13m 58s	remaining: 1m 12s
4700:	test: 0.9626996	best: 0.9626996 (4700)	total: 14m 16s	remaining: 54.5s
4800:	test: 0.9627228	best: 0.9627236 (4794)	total: 14m 34s	remaining: 36.3s
4900:	test: 0.9627365	best: 0.9627365 (4900)	total: 14m 53s	remaining: 18s
4999:	test: 0.9627613	best: 0.9627636 (4994)	total: 15m 11s	remaining: 0us

bestTest = 0.9627636184
bestIteration = 4994

Shrink model to first 4995 iterations.
CatBoost Fold 1 AUC: 0.962764


======================================================================
FOLD 2/5
======================================================================

----- LIGHTGBM -----

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.94369
[200]	valid_0's auc: 0.954156
[300]	valid_0's auc: 0.958285
[400]	valid_0's auc: 0.960039
[500]	valid_0's auc: 0.960886
[600]	valid_0's auc: 0.961416
[700]	valid_0's auc: 0.961732
[800]	valid_0's auc: 0.962009
[900]	valid_0's auc: 0.962233
[1000]	valid_0's auc: 0.962413
[1100]	valid_0's auc: 0.96262
[1200]	valid_0's auc: 0.962768
[1300]	valid_0's auc: 0.962887
[1400]	valid_0's auc: 0.962989
[1500]	valid_0's auc: 0.963077
[1600]	valid_0's auc: 0.96314
[1700]	valid_0's auc: 0.963215
[1800]	valid_0's auc: 0.963263
[1900]	valid_0's auc: 0.96333
[2000]	valid_0's auc: 0.963386
[2100]	valid_0's auc: 0.963419
[2200]	valid_0's auc: 0.963423
[2300]	valid_0's auc: 0.96345
[2400]	valid_0's auc: 0.963474
[2500]	valid_0's auc: 0.963493
[2600]	valid_0's auc: 0.963523
[2700]	valid_0's auc: 0.963557
[2800]	valid_0's auc: 0.963575
[2900]	valid_0's auc: 0.963595
[3000]	valid_0's auc: 0.963613
[3100]	valid_0's auc: 0.963617
[3200]	valid_0's auc: 0.963622
[3300]	valid_0's auc: 0.96362
[3400]	valid_0's auc: 0.963629
[3500]	valid_0's auc: 0.963622
[3600]	valid_0's auc: 0.963619
Early stopping, best iteration is:
[3436]	valid_0's auc: 0.96363
LightGBM Fold 2 AUC: 0.963630

----- XGBOOST -----
[0]	validation_0-auc:0.89513
[100]	validation_0-auc:0.94074
[200]	validation_0-auc:0.94768
[300]	validation_0-auc:0.95346
[400]	validation_0-auc:0.95681
[500]	validation_0-auc:0.95894
[600]	validation_0-auc:0.96033
[700]	validation_0-auc:0.96134
[800]	validation_0-auc:0.96206
[900]	validation_0-auc:0.96257
[1000]	validation_0-auc:0.96294
[1100]	validation_0-auc:0.96315
[1200]	validation_0-auc:0.96336
[1300]	validation_0-auc:0.96359
[1400]	validation_0-auc:0.96373
[1500]	validation_0-auc:0.96386
[1600]	validation_0-auc:0.96394
[1700]	validation_0-auc:0.96404
[1800]	validation_0-auc:0.96408
[1900]	validation_0-auc:0.96412
[2000]	validation_0-auc:0.96416
[2100]	validation_0-auc:0.96419
[2200]	validation_0-auc:0.96422
[2300]	validation_0-auc:0.96422
[2400]	validation_0-auc:0.96424
[2500]	validation_0-auc:0.96424
[2600]	validation_0-auc:0.96424
[2700]	validation_0-auc:0.96423
[2800]	validation_0-auc:0.96422
[2900]	validation_0-auc:0.96421
[3000]	validation_0-auc:0.96417
[3100]	validation_0-auc:0.96417
[3200]	validation_0-auc:0.96417
[3300]	validation_0-auc:0.96414
[3400]	validation_0-auc:0.96411
[3500]	validation_0-auc:0.96408
[3600]	validation_0-auc:0.96407
[3700]	validation_0-auc:0.96405
[3800]	validation_0-auc:0.96402
[3900]	validation_0-auc:0.96399
[4000]	validation_0-auc:0.96395
[4100]	validation_0-auc:0.96392
[4200]	validation_0-auc:0.96390
[4300]	validation_0-auc:0.96386
[4400]	validation_0-auc:0.96383
[4500]	validation_0-auc:0.96380
[4600]	validation_0-auc:0.96378
[4700]	validation_0-auc:0.96375
[4800]	validation_0-auc:0.96372
[4900]	validation_0-auc:0.96370
[4999]	validation_0-auc:0.96367
XGBoost Fold 2 AUC: 0.963666

----- CATBOOST -----
0:	test: 0.9119429	best: 0.9119429 (0)	total: 225ms	remaining: 18m 46s
100:	test: 0.9344667	best: 0.9344667 (100)	total: 22.8s	remaining: 18m 27s
200:	test: 0.9404840	best: 0.9404840 (200)	total: 45.2s	remaining: 17m 59s
300:	test: 0.9442015	best: 0.9442015 (300)	total: 1m 7s	remaining: 17m 35s
400:	test: 0.9471039	best: 0.9471039 (400)	total: 1m 30s	remaining: 17m 14s
500:	test: 0.9495356	best: 0.9495356 (500)	total: 1m 52s	remaining: 16m 51s
600:	test: 0.9517952	best: 0.9517952 (600)	total: 2m 14s	remaining: 16m 26s
700:	test: 0.9533084	best: 0.9533084 (700)	total: 2m 36s	remaining: 16m 2s
800:	test: 0.9544347	best: 0.9544347 (800)	total: 2m 59s	remaining: 15m 38s
900:	test: 0.9553649	best: 0.9553649 (900)	total: 3m 20s	remaining: 15m 13s
1000:	test: 0.9562623	best: 0.9562623 (1000)	total: 3m 42s	remaining: 14m 50s
1100:	test: 0.9569642	best: 0.9569642 (1100)	total: 4m 4s	remaining: 14m 26s
1200:	test: 0.9575981	best: 0.9575981 (1200)	total: 4m 26s	remaining: 14m 3s
1300:	test: 0.9582237	best: 0.9582237 (1300)	total: 4m 48s	remaining: 13m 41s
1400:	test: 0.9587015	best: 0.9587015 (1400)	total: 5m 10s	remaining: 13m 18s
1500:	test: 0.9590700	best: 0.9590700 (1500)	total: 5m 32s	remaining: 12m 55s
1600:	test: 0.9594455	best: 0.9594455 (1600)	total: 5m 55s	remaining: 12m 34s
1700:	test: 0.9597608	best: 0.9597608 (1700)	total: 6m 17s	remaining: 12m 11s
1800:	test: 0.9600704	best: 0.9600704 (1800)	total: 6m 39s	remaining: 11m 49s
1900:	test: 0.9603497	best: 0.9603497 (1900)	total: 7m 2s	remaining: 11m 28s
2000:	test: 0.9606266	best: 0.9606266 (2000)	total: 7m 24s	remaining: 11m 6s
2100:	test: 0.9608277	best: 0.9608277 (2100)	total: 7m 47s	remaining: 10m 44s
2200:	test: 0.9610220	best: 0.9610220 (2200)	total: 8m 9s	remaining: 10m 22s
2300:	test: 0.9612399	best: 0.9612399 (2300)	total: 8m 32s	remaining: 10m
2400:	test: 0.9613985	best: 0.9613985 (2400)	total: 8m 54s	remaining: 9m 38s
2500:	test: 0.9615171	best: 0.9615171 (2500)	total: 9m 17s	remaining: 9m 16s
2600:	test: 0.9616575	best: 0.9616575 (2599)	total: 9m 39s	remaining: 8m 54s
2700:	test: 0.9617794	best: 0.9617794 (2700)	total: 10m 2s	remaining: 8m 32s
2800:	test: 0.9619114	best: 0.9619114 (2800)	total: 10m 24s	remaining: 8m 10s
2900:	test: 0.9620371	best: 0.9620371 (2900)	total: 10m 46s	remaining: 7m 47s
3000:	test: 0.9621586	best: 0.9621586 (3000)	total: 11m 9s	remaining: 7m 25s
3100:	test: 0.9622732	best: 0.9622733 (3099)	total: 11m 31s	remaining: 7m 3s
3200:	test: 0.9623603	best: 0.9623603 (3200)	total: 11m 54s	remaining: 6m 41s
3300:	test: 0.9624519	best: 0.9624519 (3300)	total: 12m 17s	remaining: 6m 19s
3400:	test: 0.9625101	best: 0.9625101 (3400)	total: 12m 39s	remaining: 5m 57s
3500:	test: 0.9625785	best: 0.9625785 (3500)	total: 13m 2s	remaining: 5m 34s
3600:	test: 0.9626372	best: 0.9626372 (3600)	total: 13m 24s	remaining: 5m 12s
3700:	test: 0.9626945	best: 0.9626945 (3700)	total: 13m 47s	remaining: 4m 50s
3800:	test: 0.9627638	best: 0.9627638 (3800)	total: 14m 10s	remaining: 4m 28s
3900:	test: 0.9628172	best: 0.9628172 (3900)	total: 14m 32s	remaining: 4m 5s
4000:	test: 0.9628625	best: 0.9628641 (3996)	total: 14m 55s	remaining: 3m 43s
4100:	test: 0.9629035	best: 0.9629035 (4100)	total: 15m 18s	remaining: 3m 21s
4200:	test: 0.9629538	best: 0.9629545 (4197)	total: 15m 40s	remaining: 2m 58s
4300:	test: 0.9629956	best: 0.9629956 (4300)	total: 16m 2s	remaining: 2m 36s
4400:	test: 0.9630467	best: 0.9630467 (4400)	total: 16m 25s	remaining: 2m 14s
4500:	test: 0.9630575	best: 0.9630596 (4496)	total: 16m 48s	remaining: 1m 51s
4600:	test: 0.9630811	best: 0.9630811 (4600)	total: 17m 10s	remaining: 1m 29s
4700:	test: 0.9631175	best: 0.9631175 (4700)	total: 17m 33s	remaining: 1m 6s
4800:	test: 0.9631423	best: 0.9631423 (4800)	total: 17m 55s	remaining: 44.6s
4900:	test: 0.9631708	best: 0.9631714 (4898)	total: 18m 18s	remaining: 22.2s
4999:	test: 0.9632044	best: 0.9632044 (4999)	total: 18m 41s	remaining: 0us

bestTest = 0.9632043704
bestIteration = 4999

CatBoost Fold 2 AUC: 0.963204


======================================================================
FOLD 3/5
======================================================================

----- LIGHTGBM -----

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.945219
[200]	valid_0's auc: 0.955435
[300]	valid_0's auc: 0.959004
[400]	valid_0's auc: 0.960607
[500]	valid_0's auc: 0.961482
[600]	valid_0's auc: 0.961964
[700]	valid_0's auc: 0.962334
[800]	valid_0's auc: 0.962625
[900]	valid_0's auc: 0.962817
[1000]	valid_0's auc: 0.962901
[1100]	valid_0's auc: 0.963035
[1200]	valid_0's auc: 0.963208
[1300]	valid_0's auc: 0.963362
[1400]	valid_0's auc: 0.963457
[1500]	valid_0's auc: 0.963548
[1600]	valid_0's auc: 0.96362
[1700]	valid_0's auc: 0.963673
[1800]	valid_0's auc: 0.963714
[1900]	valid_0's auc: 0.963787
[2000]	valid_0's auc: 0.96387
[2100]	valid_0's auc: 0.963897
[2200]	valid_0's auc: 0.963957
[2300]	valid_0's auc: 0.963997
[2400]	valid_0's auc: 0.964023
[2500]	valid_0's auc: 0.964045
[2600]	valid_0's auc: 0.964058
[2700]	valid_0's auc: 0.964058
[2800]	valid_0's auc: 0.964059
Early stopping, best iteration is:
[2622]	valid_0's auc: 0.964064
LightGBM Fold 3 AUC: 0.964064

----- XGBOOST -----
[0]	validation_0-auc:0.89528
[100]	validation_0-auc:0.94156
[200]	validation_0-auc:0.94888
[300]	validation_0-auc:0.95429
[400]	validation_0-auc:0.95749
[500]	validation_0-auc:0.95950
[600]	validation_0-auc:0.96077
[700]	validation_0-auc:0.96165
[800]	validation_0-auc:0.96232
[900]	validation_0-auc:0.96277
[1000]	validation_0-auc:0.96313
[1100]	validation_0-auc:0.96340
[1200]	validation_0-auc:0.96358
[1300]	validation_0-auc:0.96374
[1400]	validation_0-auc:0.96389
[1500]	validation_0-auc:0.96400
[1600]	validation_0-auc:0.96409
[1700]	validation_0-auc:0.96417
[1800]	validation_0-auc:0.96421
[1900]	validation_0-auc:0.96426
[2000]	validation_0-auc:0.96429
[2100]	validation_0-auc:0.96431
[2200]	validation_0-auc:0.96433
[2300]	validation_0-auc:0.96434
[2400]	validation_0-auc:0.96435
[2500]	validation_0-auc:0.96435
[2600]	validation_0-auc:0.96435
[2700]	validation_0-auc:0.96434
[2800]	validation_0-auc:0.96432
[2900]	validation_0-auc:0.96431
[3000]	validation_0-auc:0.96430
[3100]	validation_0-auc:0.96428
[3200]	validation_0-auc:0.96427
[3300]	validation_0-auc:0.96425
[3400]	validation_0-auc:0.96422
[3500]	validation_0-auc:0.96418
[3600]	validation_0-auc:0.96416
[3700]	validation_0-auc:0.96412
[3800]	validation_0-auc:0.96410
[3900]	validation_0-auc:0.96406
[4000]	validation_0-auc:0.96403
[4100]	validation_0-auc:0.96401
[4200]	validation_0-auc:0.96397
[4300]	validation_0-auc:0.96395
[4400]	validation_0-auc:0.96391
[4500]	validation_0-auc:0.96387
[4600]	validation_0-auc:0.96383
[4700]	validation_0-auc:0.96379
[4800]	validation_0-auc:0.96377
[4900]	validation_0-auc:0.96373
[4999]	validation_0-auc:0.96370
XGBoost Fold 3 AUC: 0.963700

----- CATBOOST -----
0:	test: 0.9126760	best: 0.9126760 (0)	total: 225ms	remaining: 18m 45s
100:	test: 0.9357920	best: 0.9357920 (100)	total: 22.2s	remaining: 17m 55s
200:	test: 0.9414965	best: 0.9414965 (200)	total: 44s	remaining: 17m 31s
300:	test: 0.9451913	best: 0.9451913 (300)	total: 1m 6s	remaining: 17m 10s
400:	test: 0.9477978	best: 0.9477978 (400)	total: 1m 28s	remaining: 16m 49s
500:	test: 0.9504008	best: 0.9504008 (500)	total: 1m 49s	remaining: 16m 27s
600:	test: 0.9523903	best: 0.9523903 (600)	total: 2m 11s	remaining: 16m 5s
700:	test: 0.9538542	best: 0.9538542 (700)	total: 2m 33s	remaining: 15m 42s
800:	test: 0.9550959	best: 0.9550959 (800)	total: 2m 55s	remaining: 15m 19s
900:	test: 0.9559970	best: 0.9559970 (900)	total: 3m 17s	remaining: 14m 57s
1000:	test: 0.9567922	best: 0.9567922 (1000)	total: 3m 39s	remaining: 14m 35s
1100:	test: 0.9574584	best: 0.9574584 (1100)	total: 4m	remaining: 14m 11s
1200:	test: 0.9580216	best: 0.9580216 (1200)	total: 4m 21s	remaining: 13m 47s
1300:	test: 0.9585802	best: 0.9585802 (1300)	total: 4m 43s	remaining: 13m 26s
1400:	test: 0.9590367	best: 0.9590367 (1400)	total: 5m 5s	remaining: 13m 4s
1500:	test: 0.9594743	best: 0.9594743 (1500)	total: 5m 27s	remaining: 12m 42s
1600:	test: 0.9598217	best: 0.9598217 (1600)	total: 5m 49s	remaining: 12m 21s
1700:	test: 0.9601708	best: 0.9601708 (1700)	total: 6m 11s	remaining: 11m 59s
1800:	test: 0.9605060	best: 0.9605060 (1800)	total: 6m 32s	remaining: 11m 38s
1900:	test: 0.9607794	best: 0.9607794 (1900)	total: 6m 54s	remaining: 11m 15s
2000:	test: 0.9610207	best: 0.9610207 (2000)	total: 7m 16s	remaining: 10m 53s
2100:	test: 0.9612136	best: 0.9612136 (2100)	total: 7m 38s	remaining: 10m 32s
2200:	test: 0.9614315	best: 0.9614315 (2200)	total: 7m 59s	remaining: 10m 10s
2300:	test: 0.9616059	best: 0.9616059 (2300)	total: 8m 21s	remaining: 9m 48s
2400:	test: 0.9617649	best: 0.9617649 (2400)	total: 8m 43s	remaining: 9m 27s
2500:	test: 0.9619034	best: 0.9619035 (2497)	total: 9m 6s	remaining: 9m 5s
2600:	test: 0.9620617	best: 0.9620617 (2600)	total: 9m 28s	remaining: 8m 44s
2700:	test: 0.9621924	best: 0.9621924 (2700)	total: 9m 50s	remaining: 8m 22s
2800:	test: 0.9623027	best: 0.9623027 (2800)	total: 10m 12s	remaining: 8m
2900:	test: 0.9624050	best: 0.9624050 (2900)	total: 10m 34s	remaining: 7m 39s
3000:	test: 0.9625112	best: 0.9625112 (3000)	total: 10m 56s	remaining: 7m 17s
3100:	test: 0.9626050	best: 0.9626050 (3100)	total: 11m 18s	remaining: 6m 55s
3200:	test: 0.9626866	best: 0.9626866 (3200)	total: 11m 41s	remaining: 6m 34s
3300:	test: 0.9627706	best: 0.9627706 (3300)	total: 12m 3s	remaining: 6m 12s
3400:	test: 0.9628342	best: 0.9628342 (3400)	total: 12m 25s	remaining: 5m 50s
3500:	test: 0.9628978	best: 0.9628978 (3500)	total: 12m 47s	remaining: 5m 28s
3600:	test: 0.9629797	best: 0.9629797 (3600)	total: 13m 9s	remaining: 5m 6s
3700:	test: 0.9630360	best: 0.9630360 (3700)	total: 13m 31s	remaining: 4m 44s
3800:	test: 0.9630948	best: 0.9630948 (3800)	total: 13m 53s	remaining: 4m 23s
3900:	test: 0.9631557	best: 0.9631557 (3900)	total: 14m 16s	remaining: 4m 1s
4000:	test: 0.9632039	best: 0.9632039 (4000)	total: 14m 38s	remaining: 3m 39s
4100:	test: 0.9632627	best: 0.9632627 (4100)	total: 15m 1s	remaining: 3m 17s
4200:	test: 0.9633092	best: 0.9633092 (4200)	total: 15m 23s	remaining: 2m 55s
4300:	test: 0.9633411	best: 0.9633416 (4296)	total: 15m 45s	remaining: 2m 33s
4400:	test: 0.9633884	best: 0.9633888 (4397)	total: 16m 8s	remaining: 2m 11s
4500:	test: 0.9634151	best: 0.9634151 (4500)	total: 16m 30s	remaining: 1m 49s
4600:	test: 0.9634643	best: 0.9634643 (4598)	total: 16m 53s	remaining: 1m 27s
4700:	test: 0.9635014	best: 0.9635014 (4700)	total: 17m 15s	remaining: 1m 5s
4800:	test: 0.9635351	best: 0.9635351 (4800)	total: 17m 38s	remaining: 43.9s
4900:	test: 0.9635583	best: 0.9635588 (4899)	total: 18m	remaining: 21.8s
4999:	test: 0.9635786	best: 0.9635790 (4998)	total: 18m 22s	remaining: 0us

bestTest = 0.963578994
bestIteration = 4998

Shrink model to first 4999 iterations.
CatBoost Fold 3 AUC: 0.963579


======================================================================
FOLD 4/5
======================================================================

----- LIGHTGBM -----

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.945265
[200]	valid_0's auc: 0.955953
[300]	valid_0's auc: 0.959607
[400]	valid_0's auc: 0.96133
[500]	valid_0's auc: 0.962109
[600]	valid_0's auc: 0.962564
[700]	valid_0's auc: 0.962908
[800]	valid_0's auc: 0.96316
[900]	valid_0's auc: 0.963382
[1000]	valid_0's auc: 0.963522
[1100]	valid_0's auc: 0.963591
[1200]	valid_0's auc: 0.96372
[1300]	valid_0's auc: 0.963796
[1400]	valid_0's auc: 0.963876
[1500]	valid_0's auc: 0.963958
[1600]	valid_0's auc: 0.964024
[1700]	valid_0's auc: 0.964096
[1800]	valid_0's auc: 0.96414
[1900]	valid_0's auc: 0.964176
[2000]	valid_0's auc: 0.964211
[2100]	valid_0's auc: 0.964225
[2200]	valid_0's auc: 0.964269
[2300]	valid_0's auc: 0.964285
[2400]	valid_0's auc: 0.964299
[2500]	valid_0's auc: 0.96431
[2600]	valid_0's auc: 0.964318
[2700]	valid_0's auc: 0.964343
[2800]	valid_0's auc: 0.964342
[2900]	valid_0's auc: 0.964358
[3000]	valid_0's auc: 0.964369
[3100]	valid_0's auc: 0.96437
[3200]	valid_0's auc: 0.964394
[3300]	valid_0's auc: 0.964413
[3400]	valid_0's auc: 0.964424
[3500]	valid_0's auc: 0.964428
[3600]	valid_0's auc: 0.964421
Early stopping, best iteration is:
[3449]	valid_0's auc: 0.964436
LightGBM Fold 4 AUC: 0.964436

----- XGBOOST -----
[0]	validation_0-auc:0.89651
[100]	validation_0-auc:0.94189
[200]	validation_0-auc:0.94926
[300]	validation_0-auc:0.95476
[400]	validation_0-auc:0.95829
[500]	validation_0-auc:0.96016
[600]	validation_0-auc:0.96153
[700]	validation_0-auc:0.96241
[800]	validation_0-auc:0.96300
[900]	validation_0-auc:0.96345
[1000]	validation_0-auc:0.96385
[1100]	validation_0-auc:0.96412
[1200]	validation_0-auc:0.96431
[1300]	validation_0-auc:0.96447
[1400]	validation_0-auc:0.96459
[1500]	validation_0-auc:0.96470
[1600]	validation_0-auc:0.96478
[1700]	validation_0-auc:0.96485
[1800]	validation_0-auc:0.96491
[1900]	validation_0-auc:0.96495
[2000]	validation_0-auc:0.96497
[2100]	validation_0-auc:0.96500
[2200]	validation_0-auc:0.96502
[2300]	validation_0-auc:0.96502
[2400]	validation_0-auc:0.96503
[2500]	validation_0-auc:0.96503
[2600]	validation_0-auc:0.96503
[2700]	validation_0-auc:0.96502
[2800]	validation_0-auc:0.96500
[2900]	validation_0-auc:0.96499
[3000]	validation_0-auc:0.96497
[3100]	validation_0-auc:0.96496
[3200]	validation_0-auc:0.96495
[3300]	validation_0-auc:0.96492
[3400]	validation_0-auc:0.96490
[3500]	validation_0-auc:0.96489
[3600]	validation_0-auc:0.96486
[3700]	validation_0-auc:0.96483
[3800]	validation_0-auc:0.96481
[3900]	validation_0-auc:0.96480
[4000]	validation_0-auc:0.96477
[4100]	validation_0-auc:0.96475
[4200]	validation_0-auc:0.96473
[4300]	validation_0-auc:0.96470
[4400]	validation_0-auc:0.96467
[4500]	validation_0-auc:0.96465
[4600]	validation_0-auc:0.96462
[4700]	validation_0-auc:0.96459
[4800]	validation_0-auc:0.96455
[4900]	validation_0-auc:0.96453
[4999]	validation_0-auc:0.96448
XGBoost Fold 4 AUC: 0.964485

----- CATBOOST -----
0:	test: 0.9122465	best: 0.9122465 (0)	total: 546ms	remaining: 45m 27s
100:	test: 0.9357171	best: 0.9357171 (100)	total: 46.8s	remaining: 37m 50s
200:	test: 0.9417189	best: 0.9417189 (200)	total: 1m 33s	remaining: 37m 4s
300:	test: 0.9455331	best: 0.9455331 (300)	total: 2m 15s	remaining: 35m 22s
400:	test: 0.9484341	best: 0.9484341 (400)	total: 3m 10s	remaining: 36m 25s
500:	test: 0.9510242	best: 0.9510242 (500)	total: 4m 5s	remaining: 36m 40s
600:	test: 0.9530231	best: 0.9530231 (600)	total: 4m 27s	remaining: 32m 40s
700:	test: 0.9545706	best: 0.9545706 (700)	total: 4m 51s	remaining: 29m 48s
800:	test: 0.9557147	best: 0.9557147 (800)	total: 5m 18s	remaining: 27m 47s
900:	test: 0.9566712	best: 0.9566712 (900)	total: 5m 45s	remaining: 26m 11s
1000:	test: 0.9574954	best: 0.9574954 (1000)	total: 6m 12s	remaining: 24m 49s
1100:	test: 0.9582351	best: 0.9582351 (1100)	total: 7m	remaining: 24m 49s
1200:	test: 0.9588535	best: 0.9588535 (1200)	total: 7m 57s	remaining: 25m 10s
1300:	test: 0.9594071	best: 0.9594071 (1300)	total: 8m 55s	remaining: 25m 23s
1400:	test: 0.9598727	best: 0.9598727 (1400)	total: 9m 51s	remaining: 25m 18s
1500:	test: 0.9602231	best: 0.9602231 (1500)	total: 10m 43s	remaining: 25m
1600:	test: 0.9605863	best: 0.9605863 (1600)	total: 11m 39s	remaining: 24m 44s
1700:	test: 0.9608741	best: 0.9608741 (1700)	total: 12m 32s	remaining: 24m 18s
1800:	test: 0.9611759	best: 0.9611759 (1800)	total: 13m 31s	remaining: 24m 1s
1900:	test: 0.9614416	best: 0.9614416 (1900)	total: 14m 25s	remaining: 23m 30s
2000:	test: 0.9617050	best: 0.9617052 (1999)	total: 15m 20s	remaining: 22m 59s
2100:	test: 0.9619114	best: 0.9619114 (2100)	total: 16m 16s	remaining: 22m 27s
2200:	test: 0.9621280	best: 0.9621280 (2200)	total: 17m 13s	remaining: 21m 54s
2300:	test: 0.9623062	best: 0.9623062 (2300)	total: 18m 11s	remaining: 21m 20s
2400:	test: 0.9624478	best: 0.9624478 (2400)	total: 18m 59s	remaining: 20m 33s
2500:	test: 0.9626322	best: 0.9626322 (2500)	total: 19m 45s	remaining: 19m 44s
2600:	test: 0.9627689	best: 0.9627689 (2600)	total: 20m 41s	remaining: 19m 5s
2700:	test: 0.9628855	best: 0.9628855 (2700)	total: 21m 38s	remaining: 18m 24s
2800:	test: 0.9630173	best: 0.9630173 (2800)	total: 22m 30s	remaining: 17m 40s
2900:	test: 0.9631044	best: 0.9631047 (2899)	total: 23m 25s	remaining: 16m 56s
3000:	test: 0.9631867	best: 0.9631867 (3000)	total: 24m 24s	remaining: 16m 15s
3100:	test: 0.9632746	best: 0.9632746 (3100)	total: 25m 19s	remaining: 15m 30s
3200:	test: 0.9633728	best: 0.9633728 (3200)	total: 25m 44s	remaining: 14m 28s
3300:	test: 0.9634543	best: 0.9634545 (3299)	total: 26m 7s	remaining: 13m 26s
3400:	test: 0.9635330	best: 0.9635330 (3399)	total: 26m 32s	remaining: 12m 28s
3500:	test: 0.9635916	best: 0.9635917 (3499)	total: 26m 56s	remaining: 11m 31s
3600:	test: 0.9636671	best: 0.9636671 (3600)	total: 27m 19s	remaining: 10m 36s
3700:	test: 0.9637141	best: 0.9637141 (3700)	total: 27m 43s	remaining: 9m 43s
3800:	test: 0.9637745	best: 0.9637748 (3799)	total: 28m 6s	remaining: 8m 52s
3900:	test: 0.9638285	best: 0.9638285 (3900)	total: 28m 38s	remaining: 8m 4s
4000:	test: 0.9638880	best: 0.9638880 (4000)	total: 29m 38s	remaining: 7m 24s
4100:	test: 0.9639283	best: 0.9639283 (4100)	total: 30m 4s	remaining: 6m 35s
4200:	test: 0.9639736	best: 0.9639739 (4197)	total: 30m 28s	remaining: 5m 47s
4300:	test: 0.9640125	best: 0.9640125 (4300)	total: 30m 52s	remaining: 5m 1s
4400:	test: 0.9640416	best: 0.9640432 (4389)	total: 31m 15s	remaining: 4m 15s
4500:	test: 0.9640948	best: 0.9640948 (4500)	total: 31m 39s	remaining: 3m 30s
4600:	test: 0.9641186	best: 0.9641186 (4600)	total: 32m 2s	remaining: 2m 46s
4700:	test: 0.9641570	best: 0.9641570 (4700)	total: 32m 25s	remaining: 2m 3s
4800:	test: 0.9641818	best: 0.9641818 (4800)	total: 32m 49s	remaining: 1m 21s
4900:	test: 0.9642024	best: 0.9642024 (4900)	total: 33m 12s	remaining: 40.3s
4999:	test: 0.9642322	best: 0.9642325 (4994)	total: 33m 36s	remaining: 0us

bestTest = 0.9642325409
bestIteration = 4994

Shrink model to first 4995 iterations.
CatBoost Fold 4 AUC: 0.964233


======================================================================
FOLD 5/5
======================================================================

----- LIGHTGBM -----

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.944532
[200]	valid_0's auc: 0.954727
[300]	valid_0's auc: 0.958341
[400]	valid_0's auc: 0.960145
[500]	valid_0's auc: 0.960951
[600]	valid_0's auc: 0.961499
[700]	valid_0's auc: 0.961789
[800]	valid_0's auc: 0.962044
[900]	valid_0's auc: 0.962246
[1000]	valid_0's auc: 0.96245
[1100]	valid_0's auc: 0.962544
[1200]	valid_0's auc: 0.96267
[1300]	valid_0's auc: 0.962774
[1400]	valid_0's auc: 0.962848
[1500]	valid_0's auc: 0.962921
[1600]	valid_0's auc: 0.963004
[1700]	valid_0's auc: 0.963087
[1800]	valid_0's auc: 0.963116
[1900]	valid_0's auc: 0.963154
[2000]	valid_0's auc: 0.96319
[2100]	valid_0's auc: 0.963225
[2200]	valid_0's auc: 0.96326
[2300]	valid_0's auc: 0.963292
[2400]	valid_0's auc: 0.963333
[2500]	valid_0's auc: 0.963351
[2600]	valid_0's auc: 0.963379
[2700]	valid_0's auc: 0.963395
[2800]	valid_0's auc: 0.963401
[2900]	valid_0's auc: 0.963419
[3000]	valid_0's auc: 0.963441
[3100]	valid_0's auc: 0.963441
[3200]	valid_0's auc: 0.963455
[3300]	valid_0's auc: 0.963467
[3400]	valid_0's auc: 0.963471
[3500]	valid_0's auc: 0.963484
[3600]	valid_0's auc: 0.963482
[3700]	valid_0's auc: 0.963479
Early stopping, best iteration is:
[3530]	valid_0's auc: 0.96349
LightGBM Fold 5 AUC: 0.963490

----- XGBOOST -----
[0]	validation_0-auc:0.89549
[100]	validation_0-auc:0.94111
[200]	validation_0-auc:0.94818
[300]	validation_0-auc:0.95399
[400]	validation_0-auc:0.95700
[500]	validation_0-auc:0.95900
[600]	validation_0-auc:0.96033
[700]	validation_0-auc:0.96124
[800]	validation_0-auc:0.96185
[900]	validation_0-auc:0.96228
[1000]	validation_0-auc:0.96266
[1100]	validation_0-auc:0.96296
[1200]	validation_0-auc:0.96319
[1300]	validation_0-auc:0.96336
[1400]	validation_0-auc:0.96350
[1500]	validation_0-auc:0.96362
[1600]	validation_0-auc:0.96371
[1700]	validation_0-auc:0.96382
[1800]	validation_0-auc:0.96386
[1900]	validation_0-auc:0.96390
[2000]	validation_0-auc:0.96394
[2100]	validation_0-auc:0.96397
[2200]	validation_0-auc:0.96399
[2300]	validation_0-auc:0.96401
[2400]	validation_0-auc:0.96400
[2500]	validation_0-auc:0.96402
[2600]	validation_0-auc:0.96403
[2700]	validation_0-auc:0.96402
[2800]	validation_0-auc:0.96400
[2900]	validation_0-auc:0.96399
[3000]	validation_0-auc:0.96398
[3100]	validation_0-auc:0.96397
[3200]	validation_0-auc:0.96395
[3300]	validation_0-auc:0.96394
[3400]	validation_0-auc:0.96391
[3500]	validation_0-auc:0.96389
[3600]	validation_0-auc:0.96386
[3700]	validation_0-auc:0.96383
[3800]	validation_0-auc:0.96381
[3900]	validation_0-auc:0.96378
[4000]	validation_0-auc:0.96376
[4100]	validation_0-auc:0.96373
[4200]	validation_0-auc:0.96369
[4300]	validation_0-auc:0.96367
[4400]	validation_0-auc:0.96364
[4500]	validation_0-auc:0.96361
[4600]	validation_0-auc:0.96357
[4700]	validation_0-auc:0.96354
[4800]	validation_0-auc:0.96352
[4900]	validation_0-auc:0.96349
[4999]	validation_0-auc:0.96348
XGBoost Fold 5 AUC: 0.963475

----- CATBOOST -----
0:	test: 0.9132438	best: 0.9132438 (0)	total: 236ms	remaining: 19m 41s
100:	test: 0.9349097	best: 0.9349097 (100)	total: 24.1s	remaining: 19m 30s
200:	test: 0.9408597	best: 0.9408597 (200)	total: 48.2s	remaining: 19m 10s
300:	test: 0.9447602	best: 0.9447602 (300)	total: 1m 12s	remaining: 18m 44s
400:	test: 0.9477425	best: 0.9477425 (400)	total: 1m 36s	remaining: 18m 21s
500:	test: 0.9499894	best: 0.9499894 (500)	total: 1m 59s	remaining: 17m 54s
600:	test: 0.9517744	best: 0.9517744 (600)	total: 2m 23s	remaining: 17m 30s
700:	test: 0.9534185	best: 0.9534185 (700)	total: 2m 47s	remaining: 17m 4s
800:	test: 0.9546163	best: 0.9546163 (800)	total: 3m 10s	remaining: 16m 38s
900:	test: 0.9555221	best: 0.9555221 (900)	total: 3m 34s	remaining: 16m 14s
1000:	test: 0.9564346	best: 0.9564346 (1000)	total: 3m 57s	remaining: 15m 49s
1100:	test: 0.9571309	best: 0.9571309 (1100)	total: 4m 21s	remaining: 15m 26s
1200:	test: 0.9577093	best: 0.9577093 (1200)	total: 4m 45s	remaining: 15m 2s
1300:	test: 0.9581816	best: 0.9581816 (1300)	total: 5m 8s	remaining: 14m 37s
1400:	test: 0.9586974	best: 0.9586974 (1400)	total: 5m 32s	remaining: 14m 13s
1500:	test: 0.9591857	best: 0.9591857 (1500)	total: 5m 55s	remaining: 13m 49s
1600:	test: 0.9596006	best: 0.9596006 (1600)	total: 6m 19s	remaining: 13m 26s
1700:	test: 0.9599234	best: 0.9599234 (1700)	total: 6m 43s	remaining: 13m 2s
1800:	test: 0.9602159	best: 0.9602159 (1800)	total: 7m 7s	remaining: 12m 39s
1900:	test: 0.9604814	best: 0.9604814 (1900)	total: 7m 31s	remaining: 12m 15s
2000:	test: 0.9607091	best: 0.9607091 (1999)	total: 7m 54s	remaining: 11m 51s
2100:	test: 0.9609348	best: 0.9609348 (2100)	total: 8m 18s	remaining: 11m 28s
2200:	test: 0.9611226	best: 0.9611226 (2200)	total: 8m 42s	remaining: 11m 4s
2300:	test: 0.9613176	best: 0.9613179 (2299)	total: 9m 6s	remaining: 10m 41s
2400:	test: 0.9614690	best: 0.9614690 (2400)	total: 9m 30s	remaining: 10m 17s
2500:	test: 0.9616341	best: 0.9616341 (2500)	total: 9m 54s	remaining: 9m 54s
2600:	test: 0.9617672	best: 0.9617672 (2600)	total: 10m 18s	remaining: 9m 30s
2700:	test: 0.9618852	best: 0.9618852 (2700)	total: 10m 42s	remaining: 9m 6s
2800:	test: 0.9619981	best: 0.9619981 (2800)	total: 11m 6s	remaining: 8m 42s
2900:	test: 0.9621033	best: 0.9621033 (2900)	total: 11m 30s	remaining: 8m 19s
3000:	test: 0.9622040	best: 0.9622040 (3000)	total: 11m 53s	remaining: 7m 55s
3100:	test: 0.9622768	best: 0.9622768 (3100)	total: 12m 17s	remaining: 7m 31s
3200:	test: 0.9623798	best: 0.9623799 (3199)	total: 12m 41s	remaining: 7m 8s
3300:	test: 0.9624711	best: 0.9624711 (3300)	total: 13m 5s	remaining: 6m 44s
3400:	test: 0.9625412	best: 0.9625412 (3400)	total: 13m 29s	remaining: 6m 20s
3500:	test: 0.9626070	best: 0.9626071 (3499)	total: 13m 53s	remaining: 5m 56s
3600:	test: 0.9626654	best: 0.9626654 (3600)	total: 14m 17s	remaining: 5m 33s
3700:	test: 0.9627424	best: 0.9627424 (3700)	total: 14m 41s	remaining: 5m 9s
3800:	test: 0.9627919	best: 0.9627919 (3800)	total: 15m 5s	remaining: 4m 45s
3900:	test: 0.9628637	best: 0.9628637 (3900)	total: 15m 28s	remaining: 4m 21s
4000:	test: 0.9629090	best: 0.9629097 (3998)	total: 15m 52s	remaining: 3m 57s
4100:	test: 0.9629404	best: 0.9629430 (4093)	total: 16m 16s	remaining: 3m 34s
4200:	test: 0.9630004	best: 0.9630008 (4199)	total: 16m 40s	remaining: 3m 10s
4300:	test: 0.9630416	best: 0.9630419 (4297)	total: 17m 4s	remaining: 2m 46s
4400:	test: 0.9630791	best: 0.9630791 (4399)	total: 17m 28s	remaining: 2m 22s
4500:	test: 0.9631210	best: 0.9631210 (4500)	total: 17m 52s	remaining: 1m 58s
4600:	test: 0.9631454	best: 0.9631458 (4599)	total: 18m 16s	remaining: 1m 35s
4700:	test: 0.9631775	best: 0.9631775 (4700)	total: 18m 39s	remaining: 1m 11s
4800:	test: 0.9632036	best: 0.9632046 (4796)	total: 19m 4s	remaining: 47.4s
4900:	test: 0.9632142	best: 0.9632145 (4897)	total: 19m 28s	remaining: 23.6s
4999:	test: 0.9632338	best: 0.9632338 (4999)	total: 19m 51s	remaining: 0us

bestTest = 0.9632337907
bestIteration = 4999

CatBoost Fold 5 AUC: 0.963234

In [23]:
lgb_score = roc_auc_score(
    y,
    lgb_oof
)

print(
    f"LightGBM OOF ROC-AUC: {lgb_score:.6f}"
)

LightGBM OOF ROC-AUC: 0.963683

In [24]:
xgb_score = roc_auc_score(
    y,
    xgb_oof
)

print(
    f"XGBoost OOF ROC-AUC: {xgb_score:.6f}"
)

XGBoost OOF ROC-AUC: 0.963667

In [25]:
cat_score = roc_auc_score(
    y,
    cat_oof
)

print(
    f"CatBoost OOF ROC-AUC: {cat_score:.6f}"
)

CatBoost OOF ROC-AUC: 0.963402

In [26]:
results = pd.DataFrame({
    "Model": [
        "LightGBM",
        "XGBoost",
        "CatBoost"
    ],

    "OOF ROC-AUC": [
        lgb_score,
        xgb_score,
        cat_score
    ]
})

results.sort_values(
    "OOF ROC-AUC",
    ascending=False
)

      Model  OOF ROC-AUC
0  LightGBM     0.963683
1   XGBoost     0.963667
2  CatBoost     0.963402

In [27]:
blend_333 = (
    0.333333 * lgb_oof +
    0.333333 * xgb_oof +
    0.333334 * cat_oof
)

blend_score = roc_auc_score(
    y,
    blend_333
)

print(
    f"Equal Blend OOF ROC-AUC: "
    f"{blend_score:.6f}"
)

Equal Blend OOF ROC-AUC: 0.964577

In [28]:
weights = [
    (0.60, 0.20, 0.20),
    (0.50, 0.25, 0.25),
    (0.50, 0.20, 0.30),
    (0.40, 0.30, 0.30),
    (0.40, 0.20, 0.40),
    (0.30, 0.30, 0.40),
    (0.30, 0.40, 0.30),
    (0.20, 0.40, 0.40),
    (0.25, 0.25, 0.50),
]

blend_results = []

for lw, xw, cw in weights:

    prediction = (
        lw * lgb_oof +
        xw * xgb_oof +
        cw * cat_oof
    )

    score = roc_auc_score(
        y,
        prediction
    )

    blend_results.append({
        "LightGBM": lw,
        "XGBoost": xw,
        "CatBoost": cw,
        "ROC-AUC": score
    })

blend_results = pd.DataFrame(
    blend_results
)

blend_results.sort_values(
    "ROC-AUC",
    ascending=False
)

   LightGBM  XGBoost  CatBoost   ROC-AUC
6      0.30     0.40      0.30  0.964594
7      0.20     0.40      0.40  0.964584
5      0.30     0.30      0.40  0.964556
3      0.40     0.30      0.30  0.964553
1      0.50     0.25      0.25  0.964490
8      0.25     0.25      0.50  0.964485
4      0.40     0.20      0.40  0.964468
2      0.50     0.20      0.30  0.964453
0      0.60     0.20      0.20  0.964395

In [29]:
best_blend = blend_results.sort_values(
    "ROC-AUC",
    ascending=False
).iloc[0]

print(best_blend)

LightGBM    0.300000
XGBoost     0.400000
CatBoost    0.300000
ROC-AUC     0.964594
Name: 6, dtype: float64

In [30]:
best_lgb_weight = best_blend["LightGBM"]
best_xgb_weight = best_blend["XGBoost"]
best_cat_weight = best_blend["CatBoost"]

In [31]:
final_test_prediction = (
    best_lgb_weight * lgb_test +
    best_xgb_weight * xgb_test +
    best_cat_weight * cat_test
)

In [32]:
print(
    "Minimum:",
    final_test_prediction.min()
)

print(
    "Maximum:",
    final_test_prediction.max()
)

print(
    "Mean:",
    final_test_prediction.mean()
)

Minimum: 5.8180295077738626e-05
Maximum: 0.9999998505270016
Mean: 0.7100172850630503

In [33]:
print(X.columns.tolist())

['age', 'daily_screen_time_hours', 'social_media_hours', 'gaming_hours', 'work_study_hours', 'sleep_hours', 'notifications_per_day', 'app_opens_per_day', 'weekend_screen_time', 'gender', 'stress_level', 'academic_work_impact']

In [34]:
print(X.dtypes)

age                         float64
daily_screen_time_hours     float64
social_media_hours          float64
gaming_hours                float64
work_study_hours            float64
sleep_hours                 float64
notifications_per_day       float64
app_opens_per_day           float64
weekend_screen_time         float64
gender                     category
stress_level               category
academic_work_impact       category
dtype: object

In [35]:
print(train.head())

   id   age  daily_screen_time_hours  social_media_hours  gaming_hours  \
0   0  24.0                      NaN                1.83          1.59
1   1  19.0                     5.97                1.08           NaN
2   2  18.0                     5.09                 NaN           NaN
3   3  21.0                     6.42                1.26          1.42
4   4  26.0                    11.20                1.87          2.81

   work_study_hours  sleep_hours  notifications_per_day  app_opens_per_day  \
0              2.11         7.46                  122.0               38.0
1              3.03         8.22                   76.0               19.0
2               NaN         6.25                  134.0               60.0
3              3.36         8.85                  112.0               94.0
4              1.95         5.25                    NaN                NaN

   weekend_screen_time  gender stress_level academic_work_impact  \
0                 8.63    Male       Medium                   No
1                  NaN  Female       Medium                   No
2                 7.47  Female          Low                  Yes
3                 8.66   Other          Low                  NaN
4                13.39  Female       Medium                   No

   addicted_label
0               1
1               0
2               0
3               1
4               1

In [36]:
numeric_columns = X.select_dtypes(
    include=["number"]
).columns

for col in numeric_columns:
    score = roc_auc_score(
        y,
        X[col].fillna(X[col].median())
    )

    score = max(score, 1 - score)

    print(
        f"{col:35s} {score:.6f}"
    )

age                                 0.502115
daily_screen_time_hours             0.865372
social_media_hours                  0.817831
gaming_hours                        0.608820
work_study_hours                    0.648551
sleep_hours                         0.525288
notifications_per_day               0.507757
app_opens_per_day                   0.537697
weekend_screen_time                 0.850235

In [37]:
for col in categorical_columns:

    temp = (
        train.groupby(col)["addicted_label"]
        .agg(["mean", "count"])
        .sort_values("mean", ascending=False)
    )

    print("\n" + "=" * 60)
    print(col)
    print("=" * 60)
    print(temp.head(15))

============================================================
gender
============================================================
            mean   count
gender
Male    0.723198  223662
Female  0.703838  221595
Other   0.701020  217078

============================================================
stress_level
============================================================
                  mean   count
stress_level
High          0.711431  220873
Low           0.711160  207783
Medium        0.705663  207565

============================================================
academic_work_impact
============================================================
                          mean   count
academic_work_impact
No                    0.711029  316579
Yes                   0.707883  330566

In [38]:
submission = sample_submission.copy()

submission["addicted_label"] = final_test_prediction

submission.head()

       id  addicted_label
0  691369        0.999540
1  691370        0.947453
2  691371        0.947776
3  691372        0.991855
4  691373        0.997833

In [39]:
print(
    "Shape:",
    submission.shape
)

print(
    "Columns:",
    submission.columns.tolist()
)

print(
    "Missing:",
    submission["addicted_label"].isna().sum()
)

print(
    "Duplicate IDs:",
    submission["id"].duplicated().sum()
)

Shape: (296302, 2)
Columns: ['id', 'addicted_label']
Missing: 0
Duplicate IDs: 0

In [40]:
submission.to_csv(
    "smartphone_addiction_ensemble_improved.csv",
    index=False
)

print(
    "Saved successfully!"
)

Saved successfully!

In [41]:
X_fe = X.copy()
X_test_fe = X_test.copy()

In [42]:
for df in [X_fe, X_test_fe]:

    df["weekend_screen_diff"] = (
        df["weekend_screen_time"]
        - df["daily_screen_time_hours"]
    )

    df["weekend_screen_ratio"] = (
        df["weekend_screen_time"]
        / (df["daily_screen_time_hours"] + 0.1)
    )

    df["recreational_hours"] = (
        df["social_media_hours"]
        + df["gaming_hours"]
    )

    df["recreational_ratio"] = (
        df["recreational_hours"]
        / (df["daily_screen_time_hours"] + 0.1)
    )

    df["non_recreational_screen"] = (
        df["daily_screen_time_hours"]
        - df["recreational_hours"]
    )

In [43]:
for df in [X_fe, X_test_fe]:

    df["social_gaming_ratio"] = (
        df["social_media_hours"]
        / (df["gaming_hours"] + 0.1)
    )

    df["social_screen_ratio"] = (
        df["social_media_hours"]
        / (df["daily_screen_time_hours"] + 0.1)
    )

    df["gaming_screen_ratio"] = (
        df["gaming_hours"]
        / (df["daily_screen_time_hours"] + 0.1)
    )

In [44]:
for df in [X_fe, X_test_fe]:

    df["screen_sleep_ratio"] = (
        df["daily_screen_time_hours"]
        / (df["sleep_hours"] + 0.1)
    )

    df["screen_sleep_difference"] = (
        df["daily_screen_time_hours"]
        - df["sleep_hours"]
    )

    df["sleep_deficit_proxy"] = (
        8.0 - df["sleep_hours"]
    )

In [45]:
for df in [X_fe, X_test_fe]:

    df["notifications_per_hour"] = (
        df["notifications_per_day"]
        / (df["daily_screen_time_hours"] + 0.1)
    )

    df["opens_per_hour"] = (
        df["app_opens_per_day"]
        / (df["daily_screen_time_hours"] + 0.1)
    )

    df["notifications_per_open"] = (
        df["notifications_per_day"]
        / (df["app_opens_per_day"] + 0.1)
    )

In [46]:
for df in [X_fe, X_test_fe]:

    df["total_activity_hours"] = (
        df["social_media_hours"]
        + df["gaming_hours"]
        + df["work_study_hours"]
    )

    df["screen_plus_activity"] = (
        df["daily_screen_time_hours"]
        + df["social_media_hours"]
        + df["gaming_hours"]
    )

    df["screen_to_activity_ratio"] = (
        df["daily_screen_time_hours"]
        / (df["total_activity_hours"] + 0.1)
    )

In [47]:
for df in [X_fe, X_test_fe]:

    df["screen_time_sq"] = (
        df["daily_screen_time_hours"] ** 2
    )

    df["screen_time_cu"] = (
        df["daily_screen_time_hours"] ** 3
    )

    df["weekend_screen_sq"] = (
        df["weekend_screen_time"] ** 2
    )

    df["social_media_sq"] = (
        df["social_media_hours"] ** 2
    )

    df["gaming_sq"] = (
        df["gaming_hours"] ** 2
    )

In [48]:
print("Original features:", X.shape[1])
print("Engineered features:", X_fe.shape[1])
print("\nNew features:")

new_features = [
    col for col in X_fe.columns
    if col not in X.columns
]

print(new_features)

Original features: 12
Engineered features: 34

New features:
['weekend_screen_diff', 'weekend_screen_ratio', 'recreational_hours', 'recreational_ratio', 'non_recreational_screen', 'social_gaming_ratio', 'social_screen_ratio', 'gaming_screen_ratio', 'screen_sleep_ratio', 'screen_sleep_difference', 'sleep_deficit_proxy', 'notifications_per_hour', 'opens_per_hour', 'notifications_per_open', 'total_activity_hours', 'screen_plus_activity', 'screen_to_activity_ratio', 'screen_time_sq', 'screen_time_cu', 'weekend_screen_sq', 'social_media_sq', 'gaming_sq']

In [49]:
lgb_fe_oof = np.zeros(len(X_fe))
lgb_fe_test = np.zeros(len(X_test_fe))

In [50]:
for fold, (train_idx, valid_idx) in enumerate(folds, 1):

    print("=" * 60)
    print(f"FOLD {fold}/5")
    print("=" * 60)

    X_train_fe = X_fe.iloc[train_idx]
    X_valid_fe = X_fe.iloc[valid_idx]

    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = lgb.LGBMClassifier(
        **lgb_params
    )

    model.fit(
        X_train_fe,
        y_train,

        eval_set=[
            (X_valid_fe, y_valid)
        ],

        eval_metric="auc",

        categorical_feature=categorical_columns,

        callbacks=[
            lgb.early_stopping(
                stopping_rounds=200,
                verbose=True
            ),
            lgb.log_evaluation(
                period=100
            )
        ]
    )

    valid_pred = model.predict_proba(
        X_valid_fe
    )[:, 1]

    test_pred = model.predict_proba(
        X_test_fe
    )[:, 1]

    lgb_fe_oof[valid_idx] = valid_pred

    lgb_fe_test += (
        test_pred / len(folds)
    )

    fold_auc = roc_auc_score(
        y_valid,
        valid_pred
    )

    print(
        f"Fold {fold} ROC-AUC: {fold_auc:.6f}"
    )

============================================================
FOLD 1/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.944716
[200]	valid_0's auc: 0.955218
[300]	valid_0's auc: 0.958966
[400]	valid_0's auc: 0.960575
[500]	valid_0's auc: 0.961239
[600]	valid_0's auc: 0.961524
[700]	valid_0's auc: 0.961797
[800]	valid_0's auc: 0.962134
[900]	valid_0's auc: 0.962268
[1000]	valid_0's auc: 0.962373
[1100]	valid_0's auc: 0.962501
[1200]	valid_0's auc: 0.962632
[1300]	valid_0's auc: 0.96274
[1400]	valid_0's auc: 0.962836
[1500]	valid_0's auc: 0.96289
[1600]	valid_0's auc: 0.96294
[1700]	valid_0's auc: 0.962979
[1800]	valid_0's auc: 0.963011
[1900]	valid_0's auc: 0.963054
[2000]	valid_0's auc: 0.963073
[2100]	valid_0's auc: 0.963087
[2200]	valid_0's auc: 0.963128
[2300]	valid_0's auc: 0.963149
[2400]	valid_0's auc: 0.963169
[2500]	valid_0's auc: 0.963181
[2600]	valid_0's auc: 0.963181
[2700]	valid_0's auc: 0.963184
[2800]	valid_0's auc: 0.963185
[2900]	valid_0's auc: 0.963181
Early stopping, best iteration is:
[2795]	valid_0's auc: 0.96319
Fold 1 ROC-AUC: 0.963190
============================================================
FOLD 2/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.945114
[200]	valid_0's auc: 0.955862
[300]	valid_0's auc: 0.959692
[400]	valid_0's auc: 0.961345
[500]	valid_0's auc: 0.961995
[600]	valid_0's auc: 0.962277
[700]	valid_0's auc: 0.962561
[800]	valid_0's auc: 0.962742
[900]	valid_0's auc: 0.963023
[1000]	valid_0's auc: 0.963167
[1100]	valid_0's auc: 0.963305
[1200]	valid_0's auc: 0.963379
[1300]	valid_0's auc: 0.963465
[1400]	valid_0's auc: 0.963548
[1500]	valid_0's auc: 0.963634
[1600]	valid_0's auc: 0.963692
[1700]	valid_0's auc: 0.963715
[1800]	valid_0's auc: 0.963759
[1900]	valid_0's auc: 0.96381
[2000]	valid_0's auc: 0.96385
[2100]	valid_0's auc: 0.963889
[2200]	valid_0's auc: 0.963919
[2300]	valid_0's auc: 0.963939
[2400]	valid_0's auc: 0.963955
[2500]	valid_0's auc: 0.963983
[2600]	valid_0's auc: 0.963977
[2700]	valid_0's auc: 0.963969
Early stopping, best iteration is:
[2520]	valid_0's auc: 0.963984
Fold 2 ROC-AUC: 0.963984
============================================================
FOLD 3/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.945663
[200]	valid_0's auc: 0.95637
[300]	valid_0's auc: 0.960114
[400]	valid_0's auc: 0.961782
[500]	valid_0's auc: 0.962445
[600]	valid_0's auc: 0.962761
[700]	valid_0's auc: 0.963007
[800]	valid_0's auc: 0.963267
[900]	valid_0's auc: 0.963428
[1000]	valid_0's auc: 0.96356
[1100]	valid_0's auc: 0.963687
[1200]	valid_0's auc: 0.963771
[1300]	valid_0's auc: 0.963857
[1400]	valid_0's auc: 0.963912
[1500]	valid_0's auc: 0.963971
[1600]	valid_0's auc: 0.964056
[1700]	valid_0's auc: 0.964106
[1800]	valid_0's auc: 0.964147
[1900]	valid_0's auc: 0.964157
[2000]	valid_0's auc: 0.964171
[2100]	valid_0's auc: 0.964193
[2200]	valid_0's auc: 0.964216
[2300]	valid_0's auc: 0.964235
[2400]	valid_0's auc: 0.96428
[2500]	valid_0's auc: 0.964295
[2600]	valid_0's auc: 0.964334
[2700]	valid_0's auc: 0.964329
[2800]	valid_0's auc: 0.964336
[2900]	valid_0's auc: 0.964331
Early stopping, best iteration is:
[2775]	valid_0's auc: 0.964339
Fold 3 ROC-AUC: 0.964339
============================================================
FOLD 4/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.946392
[200]	valid_0's auc: 0.957239
[300]	valid_0's auc: 0.960924
[400]	valid_0's auc: 0.962387
[500]	valid_0's auc: 0.963112
[600]	valid_0's auc: 0.963457
[700]	valid_0's auc: 0.963724
[800]	valid_0's auc: 0.963978
[900]	valid_0's auc: 0.964094
[1000]	valid_0's auc: 0.964203
[1100]	valid_0's auc: 0.964355
[1200]	valid_0's auc: 0.964459
[1300]	valid_0's auc: 0.964542
[1400]	valid_0's auc: 0.964625
[1500]	valid_0's auc: 0.964674
[1600]	valid_0's auc: 0.964725
[1700]	valid_0's auc: 0.964801
[1800]	valid_0's auc: 0.964857
[1900]	valid_0's auc: 0.964879
[2000]	valid_0's auc: 0.964899
[2100]	valid_0's auc: 0.964942
[2200]	valid_0's auc: 0.964963
[2300]	valid_0's auc: 0.964989
[2400]	valid_0's auc: 0.964993
[2500]	valid_0's auc: 0.965003
[2600]	valid_0's auc: 0.964999
[2700]	valid_0's auc: 0.965005
[2800]	valid_0's auc: 0.964995
Early stopping, best iteration is:
[2675]	valid_0's auc: 0.965008
Fold 4 ROC-AUC: 0.965008
============================================================
FOLD 5/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.94558
[200]	valid_0's auc: 0.956034
[300]	valid_0's auc: 0.959686
[400]	valid_0's auc: 0.961265
[500]	valid_0's auc: 0.961958
[600]	valid_0's auc: 0.962326
[700]	valid_0's auc: 0.962697
[800]	valid_0's auc: 0.962923
[900]	valid_0's auc: 0.963132
[1000]	valid_0's auc: 0.963222
[1100]	valid_0's auc: 0.963386
[1200]	valid_0's auc: 0.963503
[1300]	valid_0's auc: 0.963576
[1400]	valid_0's auc: 0.963653
[1500]	valid_0's auc: 0.963714
[1600]	valid_0's auc: 0.96377
[1700]	valid_0's auc: 0.963809
[1800]	valid_0's auc: 0.963849
[1900]	valid_0's auc: 0.963854
[2000]	valid_0's auc: 0.963879
[2100]	valid_0's auc: 0.963902
[2200]	valid_0's auc: 0.963908
[2300]	valid_0's auc: 0.963915
[2400]	valid_0's auc: 0.963901
Early stopping, best iteration is:
[2253]	valid_0's auc: 0.963918
Fold 5 ROC-AUC: 0.963918

In [51]:
lgb_fe_auc = roc_auc_score(
    y,
    lgb_fe_oof
)

print(
    f"Feature Engineered LightGBM OOF ROC-AUC: "
    f"{lgb_fe_auc:.6f}"
)

Feature Engineered LightGBM OOF ROC-AUC: 0.964084

In [52]:
feature_importance = pd.DataFrame({
    "feature": X_fe.columns,
    "importance": model.feature_importances_
}).sort_values(
    "importance",
    ascending=False
)

print(feature_importance.to_string(index=False))

                 feature  importance
   notifications_per_day       13837
       app_opens_per_day       12030
     weekend_screen_time        9576
        work_study_hours        8209
 daily_screen_time_hours        6229
      social_media_hours        5811
             sleep_hours        5498
screen_to_activity_ratio        5337
  notifications_per_open        4856
     social_screen_ratio        4678
                     age        4592
            gaming_hours        4503
     gaming_screen_ratio        4367
  notifications_per_hour        4274
          opens_per_hour        4104
     social_gaming_ratio        4023
     weekend_screen_diff        3629
    total_activity_hours        3425
    weekend_screen_ratio        3314
     sleep_deficit_proxy        3312
      recreational_ratio        3272
 screen_sleep_difference        3083
      screen_sleep_ratio        3060
      recreational_hours        2629
 non_recreational_screen        2534
    screen_plus_activity        2295
       weekend_screen_sq        1550
                  gender        1208
            stress_level        1149
          screen_time_sq         988
         social_media_sq         795
    academic_work_impact         731
               gaming_sq         705
          screen_time_cu          83

In [53]:
original_features = set(X.columns)

feature_importance["type"] = feature_importance["feature"].apply(
    lambda x: "Original" if x in original_features else "Engineered"
)

print(
    feature_importance.groupby("type")["importance"]
    .sum()
)

type
Engineered    66313
Original      73373
Name: importance, dtype: int32

In [54]:
interaction_features = [
    ("notifications_per_day", "daily_screen_time_hours"),
    ("app_opens_per_day", "daily_screen_time_hours"),
    ("notifications_per_day", "app_opens_per_day"),
    ("social_media_hours", "daily_screen_time_hours"),
    ("gaming_hours", "daily_screen_time_hours"),
    ("work_study_hours", "daily_screen_time_hours"),
    ("sleep_hours", "daily_screen_time_hours"),
    ("social_media_hours", "weekend_screen_time"),
    ("gaming_hours", "weekend_screen_time"),
    ("notifications_per_day", "social_media_hours"),
    ("app_opens_per_day", "social_media_hours"),
]

In [55]:
for df in [X_fe, X_test_fe]:

    for col1, col2 in interaction_features:

        new_col = f"{col1}_x_{col2}"

        df[new_col] = (
            df[col1] * df[col2]
        )

In [56]:
for df in [X_fe, X_test_fe]:

    df["social_share_of_screen"] = (
        df["social_media_hours"]
        / df["daily_screen_time_hours"]
    )

    df["gaming_share_of_screen"] = (
        df["gaming_hours"]
        / df["daily_screen_time_hours"]
    )

    df["social_plus_gaming_share"] = (
        (
            df["social_media_hours"]
            + df["gaming_hours"]
        )
        / df["daily_screen_time_hours"]
    )

In [57]:
print(
    "X_fe infinite values:",
    np.isinf(X_fe.select_dtypes(include=np.number)).sum().sum()
)

print(
    "X_test_fe infinite values:",
    np.isinf(X_test_fe.select_dtypes(include=np.number)).sum().sum()
)

X_fe infinite values: 0
X_test_fe infinite values: 0

In [58]:
print("Original features:", X.shape[1])
print("Feature-engineered features:", X_fe.shape[1])
print("Test features:", X_test_fe.shape[1])

Original features: 12
Feature-engineered features: 48
Test features: 48

In [59]:
lgb_strong_params = {
    "objective": "binary",
    "metric": "auc",
    "boosting_type": "gbdt",

    "n_estimators": 5000,
    "learning_rate": 0.03,

    "num_leaves": 127,
    "max_depth": -1,

    "min_child_samples": 20,

    "subsample": 0.85,
    "colsample_bytree": 0.85,

    "reg_alpha": 0.1,
    "reg_lambda": 1.0,

    "random_state": 42,

    "n_jobs": -1,
    "verbosity": -1
}

In [60]:
lgb_strong_oof = np.zeros(len(X_fe))
lgb_strong_test = np.zeros(len(X_test_fe))

In [61]:
for fold, (train_idx, valid_idx) in enumerate(folds, 1):

    print("=" * 70)
    print(f"FOLD {fold}/5")
    print("=" * 70)

    X_train = X_fe.iloc[train_idx]
    X_valid = X_fe.iloc[valid_idx]

    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = lgb.LGBMClassifier(
        **lgb_strong_params
    )

    model.fit(
        X_train,
        y_train,

        eval_set=[
            (X_valid, y_valid)
        ],

        eval_metric="auc",

        categorical_feature=categorical_columns,

        callbacks=[
            lgb.early_stopping(
                stopping_rounds=200,
                verbose=True
            ),
            lgb.log_evaluation(
                period=100
            )
        ]
    )

    valid_pred = model.predict_proba(
        X_valid
    )[:, 1]

    test_pred = model.predict_proba(
        X_test_fe
    )[:, 1]

    lgb_strong_oof[valid_idx] = valid_pred

    lgb_strong_test += (
        test_pred / len(folds)
    )

    fold_auc = roc_auc_score(
        y_valid,
        valid_pred
    )

    print(
        f"Fold {fold} ROC-AUC: {fold_auc:.6f}"
    )

======================================================================
FOLD 1/5
======================================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.948205
[200]	valid_0's auc: 0.958722
[300]	valid_0's auc: 0.961145
[400]	valid_0's auc: 0.962191
[500]	valid_0's auc: 0.962428
[600]	valid_0's auc: 0.962599
[700]	valid_0's auc: 0.962708
[800]	valid_0's auc: 0.962807
[900]	valid_0's auc: 0.962876
[1000]	valid_0's auc: 0.962906
[1100]	valid_0's auc: 0.962973
[1200]	valid_0's auc: 0.963027
[1300]	valid_0's auc: 0.963015
[1400]	valid_0's auc: 0.96302
Early stopping, best iteration is:
[1201]	valid_0's auc: 0.963028
Fold 1 ROC-AUC: 0.963028
======================================================================
FOLD 2/5
======================================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.948483
[200]	valid_0's auc: 0.959412
[300]	valid_0's auc: 0.961832
[400]	valid_0's auc: 0.962773
[500]	valid_0's auc: 0.963096
[600]	valid_0's auc: 0.963187
[700]	valid_0's auc: 0.96335
[800]	valid_0's auc: 0.963465
[900]	valid_0's auc: 0.963535
[1000]	valid_0's auc: 0.963563
[1100]	valid_0's auc: 0.963612
[1200]	valid_0's auc: 0.963626
[1300]	valid_0's auc: 0.963647
[1400]	valid_0's auc: 0.963665
[1500]	valid_0's auc: 0.963668
Early stopping, best iteration is:
[1353]	valid_0's auc: 0.963671
Fold 2 ROC-AUC: 0.963671
======================================================================
FOLD 3/5
======================================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.949774
[200]	valid_0's auc: 0.959651
[300]	valid_0's auc: 0.962259
[400]	valid_0's auc: 0.96305
[500]	valid_0's auc: 0.963376
[600]	valid_0's auc: 0.963555
[700]	valid_0's auc: 0.963649
[800]	valid_0's auc: 0.963774
[900]	valid_0's auc: 0.963806
[1000]	valid_0's auc: 0.963866
[1100]	valid_0's auc: 0.96391
[1200]	valid_0's auc: 0.963926
[1300]	valid_0's auc: 0.963938
[1400]	valid_0's auc: 0.963935
[1500]	valid_0's auc: 0.963938
[1600]	valid_0's auc: 0.963934
[1700]	valid_0's auc: 0.963937
[1800]	valid_0's auc: 0.963908
Early stopping, best iteration is:
[1616]	valid_0's auc: 0.963949
Fold 3 ROC-AUC: 0.963949
======================================================================
FOLD 4/5
======================================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.950112
[200]	valid_0's auc: 0.960374
[300]	valid_0's auc: 0.962957
[400]	valid_0's auc: 0.963892
[500]	valid_0's auc: 0.964127
[600]	valid_0's auc: 0.964248
[700]	valid_0's auc: 0.964345
[800]	valid_0's auc: 0.964421
[900]	valid_0's auc: 0.964457
[1000]	valid_0's auc: 0.964518
[1100]	valid_0's auc: 0.964574
[1200]	valid_0's auc: 0.964566
[1300]	valid_0's auc: 0.964583
[1400]	valid_0's auc: 0.964585
[1500]	valid_0's auc: 0.964599
[1600]	valid_0's auc: 0.964602
[1700]	valid_0's auc: 0.9646
Early stopping, best iteration is:
[1536]	valid_0's auc: 0.964613
Fold 4 ROC-AUC: 0.964613
======================================================================
FOLD 5/5
======================================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.949275
[200]	valid_0's auc: 0.959204
[300]	valid_0's auc: 0.961775
[400]	valid_0's auc: 0.962636
[500]	valid_0's auc: 0.962908
[600]	valid_0's auc: 0.963105
[700]	valid_0's auc: 0.963267
[800]	valid_0's auc: 0.963378
[900]	valid_0's auc: 0.963448
[1000]	valid_0's auc: 0.963533
[1100]	valid_0's auc: 0.963573
[1200]	valid_0's auc: 0.963596
[1300]	valid_0's auc: 0.963628
[1400]	valid_0's auc: 0.963674
[1500]	valid_0's auc: 0.963714
[1600]	valid_0's auc: 0.963716
[1700]	valid_0's auc: 0.963715
[1800]	valid_0's auc: 0.9637
Early stopping, best iteration is:
[1623]	valid_0's auc: 0.963724
Fold 5 ROC-AUC: 0.963724

In [62]:
lgb_strong_auc = roc_auc_score(
    y,
    lgb_strong_oof
)

print(
    f"Strong LightGBM OOF ROC-AUC: "
    f"{lgb_strong_auc:.6f}"
)

Strong LightGBM OOF ROC-AUC: 0.963793

In [63]:
results = pd.DataFrame({
    "Model": [
        "Original LightGBM",
        "Feature Engineered LightGBM",
        "Previous Ensemble",
        "Strong Feature Engineered LightGBM"
    ],

    "OOF ROC-AUC": [
        0.963683,
        0.964084,
        0.964594,
        lgb_strong_auc
    ]
})

print(
    results.sort_values(
        "OOF ROC-AUC",
        ascending=False
    ).to_string(index=False)
)

                             Model  OOF ROC-AUC
                 Previous Ensemble     0.964594
       Feature Engineered LightGBM     0.964084
Strong Feature Engineered LightGBM     0.963793
                 Original LightGBM     0.963683

In [64]:
X_num = X.copy()
X_test_num = X_test.copy()

for col in categorical_columns:
    X_num[col] = (
        X_num[col]
        .astype(str)
        .fillna("MISSING")
    )

    X_test_num[col] = (
        X_test_num[col]
        .astype(str)
        .fillna("MISSING")
    )

X_num = pd.get_dummies(
    X_num,
    columns=categorical_columns,
    dummy_na=True
)

X_test_num = pd.get_dummies(
    X_test_num,
    columns=categorical_columns,
    dummy_na=True
)

X_test_num = X_test_num.reindex(
    columns=X_num.columns,
    fill_value=0
)

In [65]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [66]:
lr_pipeline = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="median")
    ),
    (
        "scaler",
        StandardScaler()
    ),
    (
        "model",
        LogisticRegression(
            C=1.0,
            max_iter=1000,
            n_jobs=-1
        )
    )
])

In [67]:
lr_oof = np.zeros(len(X_num))

for fold, (train_idx, valid_idx) in enumerate(folds, 1):

    print(f"Fold {fold}/5")

    lr_pipeline.fit(
        X_num.iloc[train_idx],
        y.iloc[train_idx]
    )

    valid_pred = lr_pipeline.predict_proba(
        X_num.iloc[valid_idx]
    )[:, 1]

    lr_oof[valid_idx] = valid_pred

    print(
        f"Fold AUC: "
        f"{roc_auc_score(y.iloc[valid_idx], valid_pred):.6f}"
    )

Fold 1/5

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:1457: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Fold AUC: 0.910389
Fold 2/5

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:1457: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Fold AUC: 0.910816
Fold 3/5

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:1457: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Fold AUC: 0.911926
Fold 4/5

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:1457: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Fold AUC: 0.912668
Fold 5/5

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:1457: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Fold AUC: 0.911603

In [68]:
lr_auc = roc_auc_score(
    y,
    lr_oof
)

print(
    f"Logistic Regression OOF ROC-AUC: "
    f"{lr_auc:.6f}"
)

Logistic Regression OOF ROC-AUC: 0.911478

In [69]:
X_missing = X.copy()
X_test_missing = X_test.copy()

for col in X.columns:

    X_missing[f"{col}_missing"] = (
        X[col].isna().astype("int8")
    )

    X_test_missing[f"{col}_missing"] = (
        X_test[col].isna().astype("int8")
    )

In [70]:
print("Original features:", X.shape[1])
print("With missing indicators:", X_missing.shape[1])

Original features: 12
With missing indicators: 24

In [71]:
missing_auc = {}

for col in X.columns:

    missing_indicator = X[col].isna().astype(int)

    auc = roc_auc_score(
        y,
        missing_indicator
    )

    auc = max(auc, 1 - auc)

    missing_auc[col] = auc

missing_auc = (
    pd.Series(missing_auc)
    .sort_values(ascending=False)
)

print(missing_auc)

app_opens_per_day          0.500952
daily_screen_time_hours    0.500631
sleep_hours                0.500617
weekend_screen_time        0.500483
gaming_hours               0.500481
age                        0.500404
work_study_hours           0.500221
notifications_per_day      0.500194
stress_level               0.500082
gender                     0.500065
academic_work_impact       0.500005
social_media_hours         0.500005
dtype: float64

In [72]:
for col in X.columns:

    missing_rate = y[X[col].isna()].mean()
    present_rate = y[X[col].notna()].mean()

    print(
        f"{col:35s} "
        f"Missing: {missing_rate:.6f} | "
        f"Present: {present_rate:.6f} | "
        f"Difference: {missing_rate - present_rate:+.6f}"
    )

age                                 Missing: 0.713402 | Present: 0.709251 | Difference: +0.004151
daily_screen_time_hours             Missing: 0.711301 | Present: 0.709122 | Difference: +0.002178
social_media_hours                  Missing: 0.709415 | Present: 0.709427 | Difference: -0.000012
gaming_hours                        Missing: 0.710505 | Present: 0.709182 | Difference: +0.001324
work_study_hours                    Missing: 0.710645 | Present: 0.709326 | Difference: +0.001319
sleep_hours                         Missing: 0.713377 | Present: 0.709153 | Difference: +0.004224
notifications_per_day               Missing: 0.710242 | Present: 0.709336 | Difference: +0.000906
app_opens_per_day                   Missing: 0.712787 | Present: 0.708980 | Difference: +0.003807
weekend_screen_time                 Missing: 0.710654 | Present: 0.709187 | Difference: +0.001467
gender                              Missing: 0.708790 | Present: 0.709452 | Difference: -0.000662
stress_level                        Missing: 0.709001 | Present: 0.709461 | Difference: -0.000460
academic_work_impact                Missing: 0.709456 | Present: 0.709422 | Difference: +0.000034

In [73]:
temp = train.copy()

temp["screen_bin"] = pd.qcut(
    temp["daily_screen_time_hours"],
    q=20,
    duplicates="drop"
)

screen_stats = (
    temp.groupby(
        "screen_bin",
        observed=True
    )["addicted_label"]
    .agg(
        ["mean", "count"]
    )
)

print(screen_stats.to_string())

                    mean  count
screen_bin
(0.499, 3.19]   0.232704  29905
(3.19, 3.97]    0.297188  30119
(3.97, 4.46]    0.290117  29657
(4.46, 4.96]    0.330658  29650
(4.96, 5.48]    0.377287  29903
(5.48, 5.89]    0.420108  29540
(5.89, 6.32]    0.428801  29860
(6.32, 6.8]     0.640332  29733
(6.8, 7.27]     0.696504  29638
(7.27, 7.77]    0.749975  30033
(7.77, 8.26]    0.859709  30230
(8.26, 8.7]     0.931898  29441
(8.7, 9.12]     0.954263  29495
(9.12, 9.47]    0.993509  30657
(9.47, 9.84]    0.993439  28960
(9.84, 10.25]   0.995994  29957
(10.25, 10.74]  0.998087  29799
(10.74, 11.24]  0.999232  29931
(11.24, 11.71]  0.999593  29491
(11.71, 15.0]   0.999729  29516

In [74]:
temp["weekend_bin"] = pd.qcut(
    temp["weekend_screen_time"],
    q=20,
    duplicates="drop"
)

weekend_stats = (
    temp.groupby(
        "weekend_bin",
        observed=True
    )["addicted_label"]
    .agg(
        ["mean", "count"]
    )
)

print(weekend_stats.to_string())

                    mean  count
weekend_bin
(0.509, 4.72]   0.262568  29021
(4.72, 5.63]    0.266273  28989
(5.63, 6.17]    0.297605  29183
(6.17, 6.76]    0.346699  29080
(6.76, 7.28]    0.390026  28575
(7.28, 7.73]    0.401960  30605
(7.73, 8.2]     0.514759  27407
(8.2, 8.68]     0.626443  29634
(8.68, 9.12]    0.702546  30203
(9.12, 9.58]    0.794123  27769
(9.58, 10.01]   0.824942  28659
(10.01, 10.47]  0.909243  29871
(10.47, 10.86]  0.929162  27810
(10.86, 11.33]  0.966839  29432
(11.33, 11.75]  0.982109  28897
(11.75, 12.08]  0.993989  28946
(12.08, 12.64]  0.996746  29505
(12.64, 13.19]  0.999247  27894
(13.19, 13.96]  0.999759  29036
(13.96, 17.56]  0.999618  28790

In [75]:
temp["social_bin"] = pd.qcut(
    temp["social_media_hours"],
    q=20,
    duplicates="drop"
)

social_stats = (
    temp.groupby(
        "social_bin",
        observed=True
    )["addicted_label"]
    .agg(
        ["mean", "count"]
    )
)

print(social_stats.to_string())

                    mean  count
social_bin
(-0.001, 0.58]  0.214604  28513
(0.58, 0.85]    0.285565  27780
(0.85, 1.07]    0.310569  27939
(1.07, 1.27]    0.364721  28334
(1.27, 1.45]    0.441813  27867
(1.45, 1.62]    0.518333  26919
(1.62, 1.79]    0.587051  28621
(1.79, 1.94]    0.678996  27224
(1.94, 2.12]    0.711479  27686
(2.12, 2.31]    0.745685  28044
(2.31, 2.51]    0.806794  29233
(2.51, 2.7]     0.857242  27284
(2.7, 2.9]      0.889374  27941
(2.9, 3.16]     0.910255  27946
(3.16, 3.37]    0.954510  26907
(3.37, 3.65]    0.964565  28559
(3.65, 3.94]    0.980737  27046
(3.94, 4.33]    0.990018  28251
(4.33, 4.86]    0.997603  27536
(4.86, 8.0]     0.999676  27744

In [76]:
strong_features = [
    "daily_screen_time_hours",
    "weekend_screen_time",
    "social_media_hours",
    "work_study_hours",
    "gaming_hours",
    "sleep_hours",
    "notifications_per_day",
    "app_opens_per_day",
    "age"
]

X_hgb = X[strong_features].copy()
X_test_hgb = X_test[strong_features].copy()

print(X_hgb.shape)

(691369, 9)

In [77]:
from sklearn.ensemble import HistGradientBoostingClassifier

hgb_params = {
    "learning_rate": 0.05,
    "max_iter": 1000,
    "max_leaf_nodes": 63,
    "max_depth": None,
    "min_samples_leaf": 30,
    "l2_regularization": 1.0,
    "random_state": 42
}

In [78]:
hgb_oof = np.zeros(len(X_hgb))
hgb_test = np.zeros(len(X_test_hgb))

In [79]:
for fold, (train_idx, valid_idx) in enumerate(folds, 1):

    print("=" * 60)
    print(f"FOLD {fold}/5")
    print("=" * 60)

    model_hgb = HistGradientBoostingClassifier(
        **hgb_params
    )

    model_hgb.fit(
        X_hgb.iloc[train_idx],
        y.iloc[train_idx]
    )

    valid_pred = model_hgb.predict_proba(
        X_hgb.iloc[valid_idx]
    )[:, 1]

    test_pred = model_hgb.predict_proba(
        X_test_hgb
    )[:, 1]

    hgb_oof[valid_idx] = valid_pred

    hgb_test += (
        test_pred / len(folds)
    )

    fold_auc = roc_auc_score(
        y.iloc[valid_idx],
        valid_pred
    )

    print(
        f"Fold {fold} ROC-AUC: {fold_auc:.6f}"
    )

============================================================
FOLD 1/5
============================================================
Fold 1 ROC-AUC: 0.961583
============================================================
FOLD 2/5
============================================================
Fold 2 ROC-AUC: 0.962739
============================================================
FOLD 3/5
============================================================
Fold 3 ROC-AUC: 0.962585
============================================================
FOLD 4/5
============================================================
Fold 4 ROC-AUC: 0.963511
============================================================
FOLD 5/5
============================================================
Fold 5 ROC-AUC: 0.962187

In [80]:
hgb_auc = roc_auc_score(
    y,
    hgb_oof
)

print(
    f"HistGradientBoosting OOF ROC-AUC: "
    f"{hgb_auc:.6f}"
)

HistGradientBoosting OOF ROC-AUC: 0.962519

In [81]:
thresholds = {
    "daily_screen_time_hours": [6.3, 7.0, 7.8, 8.3, 9.1, 10.0],
    "weekend_screen_time": [7.7, 8.2, 8.7, 9.1, 10.0, 11.0],
    "social_media_hours": [1.4, 1.6, 1.8, 2.1, 2.5, 3.0]
}

for df in [X_fe, X_test_fe]:

    for col, values in thresholds.items():

        for threshold in values:

            safe_name = str(threshold).replace(".", "_")

            df[f"{col}_gt_{safe_name}"] = (
                df[col] > threshold
            ).astype("int8")

In [82]:
for df in [X_fe, X_test_fe]:

    for col, values in thresholds.items():

        for threshold in values:

            safe_name = str(threshold).replace(".", "_")

            df[f"{col}_dist_{safe_name}"] = (
                df[col] - threshold
            )

In [83]:
print("Training features:", X_fe.shape[1])
print("Test features:", X_test_fe.shape[1])

Training features: 84
Test features: 84

In [84]:
threshold_oof = np.zeros(len(X_fe))
threshold_test = np.zeros(len(X_test_fe))

In [85]:
threshold_params = {
    "objective": "binary",
    "metric": "auc",
    "boosting_type": "gbdt",

    "n_estimators": 5000,
    "learning_rate": 0.03,

    "num_leaves": 63,
    "max_depth": -1,

    "min_child_samples": 30,

    "subsample": 0.85,
    "colsample_bytree": 0.85,

    "reg_alpha": 0.1,
    "reg_lambda": 1.0,

    "random_state": 42,

    "n_jobs": -1,
    "verbosity": -1
}

In [86]:
for fold, (train_idx, valid_idx) in enumerate(folds, 1):

    print("=" * 60)
    print(f"FOLD {fold}/5")
    print("=" * 60)

    X_train = X_fe.iloc[train_idx]
    X_valid = X_fe.iloc[valid_idx]

    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = lgb.LGBMClassifier(
        **threshold_params
    )

    model.fit(
        X_train,
        y_train,

        eval_set=[
            (X_valid, y_valid)
        ],

        eval_metric="auc",

        categorical_feature=categorical_columns,

        callbacks=[
            lgb.early_stopping(
                stopping_rounds=200,
                verbose=True
            ),
            lgb.log_evaluation(
                period=100
            )
        ]
    )

    valid_pred = model.predict_proba(
        X_valid
    )[:, 1]

    test_pred = model.predict_proba(
        X_test_fe
    )[:, 1]

    threshold_oof[valid_idx] = valid_pred

    threshold_test += (
        test_pred / len(folds)
    )

    fold_auc = roc_auc_score(
        y_valid,
        valid_pred
    )

    print(
        f"Fold {fold} ROC-AUC: {fold_auc:.6f}"
    )

============================================================
FOLD 1/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.945048
[200]	valid_0's auc: 0.955537
[300]	valid_0's auc: 0.95949
[400]	valid_0's auc: 0.961301
[500]	valid_0's auc: 0.961987
[600]	valid_0's auc: 0.962424
[700]	valid_0's auc: 0.962773
[800]	valid_0's auc: 0.962986
[900]	valid_0's auc: 0.963192
[1000]	valid_0's auc: 0.963377
[1100]	valid_0's auc: 0.963475
[1200]	valid_0's auc: 0.963642
[1300]	valid_0's auc: 0.963747
[1400]	valid_0's auc: 0.963878
[1500]	valid_0's auc: 0.963996
[1600]	valid_0's auc: 0.964019
[1700]	valid_0's auc: 0.964048
[1800]	valid_0's auc: 0.964099
[1900]	valid_0's auc: 0.964159
[2000]	valid_0's auc: 0.964196
[2100]	valid_0's auc: 0.964216
[2200]	valid_0's auc: 0.964237
[2300]	valid_0's auc: 0.964272
[2400]	valid_0's auc: 0.964281
[2500]	valid_0's auc: 0.964297
[2600]	valid_0's auc: 0.96432
[2700]	valid_0's auc: 0.964334
[2800]	valid_0's auc: 0.964345
[2900]	valid_0's auc: 0.964365
[3000]	valid_0's auc: 0.964373
[3100]	valid_0's auc: 0.964353
Early stopping, best iteration is:
[2982]	valid_0's auc: 0.964375
Fold 1 ROC-AUC: 0.964375
============================================================
FOLD 2/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.945019
[200]	valid_0's auc: 0.95612
[300]	valid_0's auc: 0.959962
[400]	valid_0's auc: 0.961791
[500]	valid_0's auc: 0.962565
[600]	valid_0's auc: 0.962979
[700]	valid_0's auc: 0.963383
[800]	valid_0's auc: 0.963609
[900]	valid_0's auc: 0.963806
[1000]	valid_0's auc: 0.963989
[1100]	valid_0's auc: 0.964196
[1200]	valid_0's auc: 0.964326
[1300]	valid_0's auc: 0.964433
[1400]	valid_0's auc: 0.964546
[1500]	valid_0's auc: 0.964594
[1600]	valid_0's auc: 0.96467
[1700]	valid_0's auc: 0.964752
[1800]	valid_0's auc: 0.964827
[1900]	valid_0's auc: 0.964876
[2000]	valid_0's auc: 0.964898
[2100]	valid_0's auc: 0.964938
[2200]	valid_0's auc: 0.964963
[2300]	valid_0's auc: 0.965004
[2400]	valid_0's auc: 0.965005
[2500]	valid_0's auc: 0.965036
[2600]	valid_0's auc: 0.965056
[2700]	valid_0's auc: 0.96506
[2800]	valid_0's auc: 0.965077
[2900]	valid_0's auc: 0.965085
[3000]	valid_0's auc: 0.965098
[3100]	valid_0's auc: 0.96509
Early stopping, best iteration is:
[2999]	valid_0's auc: 0.965098
Fold 2 ROC-AUC: 0.965098
============================================================
FOLD 3/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.946113
[200]	valid_0's auc: 0.956743
[300]	valid_0's auc: 0.960438
[400]	valid_0's auc: 0.962317
[500]	valid_0's auc: 0.963065
[600]	valid_0's auc: 0.963421
[700]	valid_0's auc: 0.963768
[800]	valid_0's auc: 0.964044
[900]	valid_0's auc: 0.964296
[1000]	valid_0's auc: 0.964432
[1100]	valid_0's auc: 0.964568
[1200]	valid_0's auc: 0.96468
[1300]	valid_0's auc: 0.964771
[1400]	valid_0's auc: 0.964849
[1500]	valid_0's auc: 0.964935
[1600]	valid_0's auc: 0.964967
[1700]	valid_0's auc: 0.964997
[1800]	valid_0's auc: 0.965057
[1900]	valid_0's auc: 0.965086
[2000]	valid_0's auc: 0.965108
[2100]	valid_0's auc: 0.965153
[2200]	valid_0's auc: 0.965181
[2300]	valid_0's auc: 0.965213
[2400]	valid_0's auc: 0.965212
[2500]	valid_0's auc: 0.965213
[2600]	valid_0's auc: 0.965227
[2700]	valid_0's auc: 0.965243
[2800]	valid_0's auc: 0.965259
[2900]	valid_0's auc: 0.965261
[3000]	valid_0's auc: 0.965261
[3100]	valid_0's auc: 0.965271
[3200]	valid_0's auc: 0.965286
[3300]	valid_0's auc: 0.965295
[3400]	valid_0's auc: 0.965277
Early stopping, best iteration is:
[3240]	valid_0's auc: 0.965297
Fold 3 ROC-AUC: 0.965297
============================================================
FOLD 4/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.946667
[200]	valid_0's auc: 0.9576
[300]	valid_0's auc: 0.9613
[400]	valid_0's auc: 0.963026
[500]	valid_0's auc: 0.963747
[600]	valid_0's auc: 0.964218
[700]	valid_0's auc: 0.964457
[800]	valid_0's auc: 0.964678
[900]	valid_0's auc: 0.964849
[1000]	valid_0's auc: 0.965061
[1100]	valid_0's auc: 0.965152
[1200]	valid_0's auc: 0.965245
[1300]	valid_0's auc: 0.965317
[1400]	valid_0's auc: 0.965394
[1500]	valid_0's auc: 0.965491
[1600]	valid_0's auc: 0.965538
[1700]	valid_0's auc: 0.96559
[1800]	valid_0's auc: 0.965651
[1900]	valid_0's auc: 0.965709
[2000]	valid_0's auc: 0.965748
[2100]	valid_0's auc: 0.965806
[2200]	valid_0's auc: 0.965832
[2300]	valid_0's auc: 0.96585
[2400]	valid_0's auc: 0.965865
[2500]	valid_0's auc: 0.965874
[2600]	valid_0's auc: 0.965889
[2700]	valid_0's auc: 0.965886
[2800]	valid_0's auc: 0.965911
[2900]	valid_0's auc: 0.965918
[3000]	valid_0's auc: 0.965909
[3100]	valid_0's auc: 0.965905
Early stopping, best iteration is:
[2923]	valid_0's auc: 0.965924
Fold 4 ROC-AUC: 0.965924
============================================================
FOLD 5/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.946028
[200]	valid_0's auc: 0.956131
[300]	valid_0's auc: 0.959984
[400]	valid_0's auc: 0.961763
[500]	valid_0's auc: 0.962673
[600]	valid_0's auc: 0.963109
[700]	valid_0's auc: 0.963409
[800]	valid_0's auc: 0.963708
[900]	valid_0's auc: 0.96403
[1000]	valid_0's auc: 0.964208
[1100]	valid_0's auc: 0.964325
[1200]	valid_0's auc: 0.964409
[1300]	valid_0's auc: 0.964498
[1400]	valid_0's auc: 0.964591
[1500]	valid_0's auc: 0.964647
[1600]	valid_0's auc: 0.964686
[1700]	valid_0's auc: 0.964724
[1800]	valid_0's auc: 0.964782
[1900]	valid_0's auc: 0.964794
[2000]	valid_0's auc: 0.964829
[2100]	valid_0's auc: 0.964869
[2200]	valid_0's auc: 0.9649
[2300]	valid_0's auc: 0.96489
[2400]	valid_0's auc: 0.964916
[2500]	valid_0's auc: 0.964924
[2600]	valid_0's auc: 0.964934
[2700]	valid_0's auc: 0.964939
[2800]	valid_0's auc: 0.964953
[2900]	valid_0's auc: 0.964956
[3000]	valid_0's auc: 0.964954
[3100]	valid_0's auc: 0.964964
[3200]	valid_0's auc: 0.964964
[3300]	valid_0's auc: 0.964958
Early stopping, best iteration is:
[3163]	valid_0's auc: 0.964969
Fold 5 ROC-AUC: 0.964969

In [87]:
threshold_auc = roc_auc_score(
    y,
    threshold_oof
)

print(
    f"Threshold LightGBM OOF ROC-AUC: "
    f"{threshold_auc:.6f}"
)

Threshold LightGBM OOF ROC-AUC: 0.965130

In [88]:
print("Threshold OOF:", threshold_oof.shape)
print("XGB OOF:", xgb_oof.shape)
print("CatBoost OOF:", cat_oof.shape)
print("LGB OOF:", lgb_oof.shape)

Threshold OOF: (691369,)
XGB OOF: (691369,)
CatBoost OOF: (691369,)
LGB OOF: (691369,)

In [89]:
print(
    "Threshold LGB:",
    roc_auc_score(y, threshold_oof)
)

Threshold LGB: 0.965129806227864

In [90]:
blend_results = []

weights = [
    (0.4, 0.3, 0.3),
    (0.5, 0.25, 0.25),
    (0.5, 0.3, 0.2),
    (0.6, 0.2, 0.2),
    (0.6, 0.25, 0.15),
    (0.7, 0.15, 0.15),
    (0.7, 0.2, 0.1),
    (0.8, 0.1, 0.1),
]

for w_lgb, w_xgb, w_cat in weights:

    pred = (
        w_lgb * threshold_oof
        + w_xgb * xgb_oof
        + w_cat * cat_oof
    )

    auc = roc_auc_score(
        y,
        pred
    )

    blend_results.append({
        "LightGBM": w_lgb,
        "XGBoost": w_xgb,
        "CatBoost": w_cat,
        "ROC-AUC": auc
    })

blend_results = pd.DataFrame(
    blend_results
).sort_values(
    "ROC-AUC",
    ascending=False
)

print(
    blend_results.to_string(index=False)
)

 LightGBM  XGBoost  CatBoost  ROC-AUC
      0.6     0.25      0.15 0.965597
      0.7     0.20      0.10 0.965578
      0.6     0.20      0.20 0.965574
      0.5     0.30      0.20 0.965559
      0.7     0.15      0.15 0.965550
      0.5     0.25      0.25 0.965541
      0.8     0.10      0.10 0.965470
      0.4     0.30      0.30 0.965452

In [91]:
best_blend = blend_results.iloc[0]

print(best_blend)

LightGBM    0.600000
XGBoost     0.250000
CatBoost    0.150000
ROC-AUC     0.965597
Name: 4, dtype: float64

In [92]:
# Current best blend
best_oof_pred = (
    0.60 * threshold_oof
    + 0.25 * xgb_oof
    + 0.15 * cat_oof
)

best_test_pred = (
    0.60 * threshold_test
    + 0.25 * xgb_test
    + 0.15 * cat_test
)

In [93]:
best_auc = roc_auc_score(
    y,
    best_oof_pred
)

print(f"Best Blend OOF ROC-AUC: {best_auc:.6f}")

Best Blend OOF ROC-AUC: 0.965597

In [94]:
submission = pd.DataFrame({
    "id": test["id"],
    "addicted_label": best_test_pred
})

submission.to_csv(
    "submission_best_0965597.csv",
    index=False
)

print(submission.head())
print(submission.shape)

       id  addicted_label
0  691369        0.999457
1  691370        0.943588
2  691371        0.929540
3  691372        0.991903
4  691373        0.998004
(296302, 2)

In [95]:
import os

print(
    os.path.abspath(
        "submission_best_0965597.csv"
    )
)

print(
    submission["addicted_label"].min(),
    submission["addicted_label"].max(),
    submission["addicted_label"].mean()
)

c:\ZZZ D Drive\CRISP\Kaggle Compe\playground-series-s6e8\submission_best_0965597.csv
9.411426930788078e-05 0.9999998825606463 0.710127981317264

In [96]:
X_threshold = X.copy()
X_test_threshold = X_test.copy()

for col, values in thresholds.items():

    for threshold in values:

        safe_name = str(threshold).replace(".", "_")

        X_threshold[f"{col}_gt_{safe_name}"] = (
            X_threshold[col] > threshold
        ).astype("int8")

        X_test_threshold[f"{col}_gt_{safe_name}"] = (
            X_test_threshold[col] > threshold
        ).astype("int8")

        X_threshold[f"{col}_dist_{safe_name}"] = (
            X_threshold[col] - threshold
        )

        X_test_threshold[f"{col}_dist_{safe_name}"] = (
            X_test_threshold[col] - threshold
        )

print("Threshold-only features:", X_threshold.shape[1])

Threshold-only features: 48

In [97]:
threshold_only_oof = np.zeros(len(X_threshold))
threshold_only_test = np.zeros(len(X_test_threshold))

In [98]:
for fold, (train_idx, valid_idx) in enumerate(folds, 1):

    print("=" * 60)
    print(f"FOLD {fold}/5")
    print("=" * 60)

    X_train = X_threshold.iloc[train_idx]
    X_valid = X_threshold.iloc[valid_idx]

    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = lgb.LGBMClassifier(
        **threshold_params
    )

    model.fit(
        X_train,
        y_train,

        eval_set=[
            (X_valid, y_valid)
        ],

        eval_metric="auc",

        categorical_feature=categorical_columns,

        callbacks=[
            lgb.early_stopping(
                stopping_rounds=200,
                verbose=True
            ),
            lgb.log_evaluation(
                period=100
            )
        ]
    )

    valid_pred = model.predict_proba(
        X_valid
    )[:, 1]

    test_pred = model.predict_proba(
        X_test_threshold
    )[:, 1]

    threshold_only_oof[valid_idx] = valid_pred

    threshold_only_test += (
        test_pred / len(folds)
    )

    print(
        f"Fold {fold} ROC-AUC: "
        f"{roc_auc_score(y_valid, valid_pred):.6f}"
    )

============================================================
FOLD 1/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.943331
[200]	valid_0's auc: 0.954185
[300]	valid_0's auc: 0.958024
[400]	valid_0's auc: 0.960156
[500]	valid_0's auc: 0.961014
[600]	valid_0's auc: 0.961584
[700]	valid_0's auc: 0.96202
[800]	valid_0's auc: 0.962298
[900]	valid_0's auc: 0.962459
[1000]	valid_0's auc: 0.962677
[1100]	valid_0's auc: 0.962854
[1200]	valid_0's auc: 0.963031
[1300]	valid_0's auc: 0.96317
[1400]	valid_0's auc: 0.963348
[1500]	valid_0's auc: 0.963481
[1600]	valid_0's auc: 0.963582
[1700]	valid_0's auc: 0.963649
[1800]	valid_0's auc: 0.963737
[1900]	valid_0's auc: 0.963797
[2000]	valid_0's auc: 0.963862
[2100]	valid_0's auc: 0.963902
[2200]	valid_0's auc: 0.963955
[2300]	valid_0's auc: 0.964012
[2400]	valid_0's auc: 0.964033
[2500]	valid_0's auc: 0.96404
[2600]	valid_0's auc: 0.964059
[2700]	valid_0's auc: 0.964087
[2800]	valid_0's auc: 0.964102
[2900]	valid_0's auc: 0.964112
[3000]	valid_0's auc: 0.964112
[3100]	valid_0's auc: 0.964121
[3200]	valid_0's auc: 0.964136
[3300]	valid_0's auc: 0.96416
[3400]	valid_0's auc: 0.964165
[3500]	valid_0's auc: 0.964174
[3600]	valid_0's auc: 0.964179
[3700]	valid_0's auc: 0.964179
[3800]	valid_0's auc: 0.964184
[3900]	valid_0's auc: 0.964171
Early stopping, best iteration is:
[3784]	valid_0's auc: 0.964185
Fold 1 ROC-AUC: 0.964185
============================================================
FOLD 2/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.94304
[200]	valid_0's auc: 0.954385
[300]	valid_0's auc: 0.958665
[400]	valid_0's auc: 0.96063
[500]	valid_0's auc: 0.961608
[600]	valid_0's auc: 0.962152
[700]	valid_0's auc: 0.962572
[800]	valid_0's auc: 0.962877
[900]	valid_0's auc: 0.963111
[1000]	valid_0's auc: 0.963289
[1100]	valid_0's auc: 0.963478
[1200]	valid_0's auc: 0.963736
[1300]	valid_0's auc: 0.963919
[1400]	valid_0's auc: 0.964018
[1500]	valid_0's auc: 0.964098
[1600]	valid_0's auc: 0.964171
[1700]	valid_0's auc: 0.964273
[1800]	valid_0's auc: 0.964355
[1900]	valid_0's auc: 0.964396
[2000]	valid_0's auc: 0.964464
[2100]	valid_0's auc: 0.964511
[2200]	valid_0's auc: 0.964552
[2300]	valid_0's auc: 0.964596
[2400]	valid_0's auc: 0.964642
[2500]	valid_0's auc: 0.964684
[2600]	valid_0's auc: 0.964721
[2700]	valid_0's auc: 0.964772
[2800]	valid_0's auc: 0.96482
[2900]	valid_0's auc: 0.964844
[3000]	valid_0's auc: 0.964856
[3100]	valid_0's auc: 0.964879
[3200]	valid_0's auc: 0.9649
[3300]	valid_0's auc: 0.964903
[3400]	valid_0's auc: 0.964909
[3500]	valid_0's auc: 0.964908
[3600]	valid_0's auc: 0.964909
[3700]	valid_0's auc: 0.964911
[3800]	valid_0's auc: 0.964911
[3900]	valid_0's auc: 0.964932
[4000]	valid_0's auc: 0.964932
[4100]	valid_0's auc: 0.964937
[4200]	valid_0's auc: 0.964935
[4300]	valid_0's auc: 0.964934
[4400]	valid_0's auc: 0.964938
Early stopping, best iteration is:
[4279]	valid_0's auc: 0.964941
Fold 2 ROC-AUC: 0.964941
============================================================
FOLD 3/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.944708
[200]	valid_0's auc: 0.955564
[300]	valid_0's auc: 0.959413
[400]	valid_0's auc: 0.961208
[500]	valid_0's auc: 0.962173
[600]	valid_0's auc: 0.9627
[700]	valid_0's auc: 0.96307
[800]	valid_0's auc: 0.963401
[900]	valid_0's auc: 0.96361
[1000]	valid_0's auc: 0.963792
[1100]	valid_0's auc: 0.964038
[1200]	valid_0's auc: 0.964219
[1300]	valid_0's auc: 0.964345
[1400]	valid_0's auc: 0.964456
[1500]	valid_0's auc: 0.964563
[1600]	valid_0's auc: 0.964647
[1700]	valid_0's auc: 0.964708
[1800]	valid_0's auc: 0.964802
[1900]	valid_0's auc: 0.964843
[2000]	valid_0's auc: 0.964901
[2100]	valid_0's auc: 0.964944
[2200]	valid_0's auc: 0.965003
[2300]	valid_0's auc: 0.965025
[2400]	valid_0's auc: 0.965058
[2500]	valid_0's auc: 0.965089
[2600]	valid_0's auc: 0.965109
[2700]	valid_0's auc: 0.965145
[2800]	valid_0's auc: 0.965175
[2900]	valid_0's auc: 0.965213
[3000]	valid_0's auc: 0.965225
[3100]	valid_0's auc: 0.965233
[3200]	valid_0's auc: 0.965239
[3300]	valid_0's auc: 0.965252
[3400]	valid_0's auc: 0.965269
[3500]	valid_0's auc: 0.965284
[3600]	valid_0's auc: 0.965291
[3700]	valid_0's auc: 0.965292
[3800]	valid_0's auc: 0.965289
[3900]	valid_0's auc: 0.965284
Early stopping, best iteration is:
[3775]	valid_0's auc: 0.965296
Fold 3 ROC-AUC: 0.965296
============================================================
FOLD 4/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.944601
[200]	valid_0's auc: 0.955887
[300]	valid_0's auc: 0.959942
[400]	valid_0's auc: 0.961881
[500]	valid_0's auc: 0.962884
[600]	valid_0's auc: 0.963394
[700]	valid_0's auc: 0.963859
[800]	valid_0's auc: 0.964165
[900]	valid_0's auc: 0.964337
[1000]	valid_0's auc: 0.964507
[1100]	valid_0's auc: 0.9647
[1200]	valid_0's auc: 0.964847
[1300]	valid_0's auc: 0.964993
[1400]	valid_0's auc: 0.965084
[1500]	valid_0's auc: 0.96521
[1600]	valid_0's auc: 0.965326
[1700]	valid_0's auc: 0.9654
[1800]	valid_0's auc: 0.965463
[1900]	valid_0's auc: 0.965504
[2000]	valid_0's auc: 0.965539
[2100]	valid_0's auc: 0.965583
[2200]	valid_0's auc: 0.965628
[2300]	valid_0's auc: 0.965652
[2400]	valid_0's auc: 0.965676
[2500]	valid_0's auc: 0.96569
[2600]	valid_0's auc: 0.965692
[2700]	valid_0's auc: 0.965714
[2800]	valid_0's auc: 0.965719
[2900]	valid_0's auc: 0.965727
[3000]	valid_0's auc: 0.96574
[3100]	valid_0's auc: 0.965747
[3200]	valid_0's auc: 0.965762
[3300]	valid_0's auc: 0.965758
[3400]	valid_0's auc: 0.965764
[3500]	valid_0's auc: 0.965774
[3600]	valid_0's auc: 0.965766
Early stopping, best iteration is:
[3490]	valid_0's auc: 0.965774
Fold 4 ROC-AUC: 0.965774
============================================================
FOLD 5/5
============================================================

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 200 rounds
[100]	valid_0's auc: 0.944467
[200]	valid_0's auc: 0.954612
[300]	valid_0's auc: 0.958804
[400]	valid_0's auc: 0.960644
[500]	valid_0's auc: 0.961689
[600]	valid_0's auc: 0.962292
[700]	valid_0's auc: 0.962651
[800]	valid_0's auc: 0.963007
[900]	valid_0's auc: 0.963277
[1000]	valid_0's auc: 0.963416
[1100]	valid_0's auc: 0.963612
[1200]	valid_0's auc: 0.963782
[1300]	valid_0's auc: 0.96394
[1400]	valid_0's auc: 0.964009
[1500]	valid_0's auc: 0.964122
[1600]	valid_0's auc: 0.964242
[1700]	valid_0's auc: 0.964371
[1800]	valid_0's auc: 0.964415
[1900]	valid_0's auc: 0.96446
[2000]	valid_0's auc: 0.964505
[2100]	valid_0's auc: 0.964547
[2200]	valid_0's auc: 0.964607
[2300]	valid_0's auc: 0.964635
[2400]	valid_0's auc: 0.964664
[2500]	valid_0's auc: 0.964669
[2600]	valid_0's auc: 0.964702
[2700]	valid_0's auc: 0.964731
[2800]	valid_0's auc: 0.964738
[2900]	valid_0's auc: 0.964754
[3000]	valid_0's auc: 0.96477
[3100]	valid_0's auc: 0.964787
[3200]	valid_0's auc: 0.96479
[3300]	valid_0's auc: 0.96481
[3400]	valid_0's auc: 0.96481
[3500]	valid_0's auc: 0.964825
[3600]	valid_0's auc: 0.964834
[3700]	valid_0's auc: 0.964832
[3800]	valid_0's auc: 0.964845
[3900]	valid_0's auc: 0.964834
Early stopping, best iteration is:
[3798]	valid_0's auc: 0.964846
Fold 5 ROC-AUC: 0.964846

In [99]:
threshold_only_auc = roc_auc_score(
    y,
    threshold_only_oof
)

print(
    f"Threshold-only LightGBM OOF ROC-AUC: "
    f"{threshold_only_auc:.6f}"
)

Threshold-only LightGBM OOF ROC-AUC: 0.965005

In [100]:
blend_results_fine = []

for w_lgb in np.arange(0.50, 0.91, 0.01):

    for w_xgb in np.arange(0.05, 0.46, 0.01):

        w_cat = 1.0 - w_lgb - w_xgb

        # CatBoost must have at least 5% weight
        if w_cat < 0.05:
            continue

        pred = (
            w_lgb * threshold_oof
            + w_xgb * xgb_oof
            + w_cat * cat_oof
        )

        auc = roc_auc_score(
            y,
            pred
        )

        blend_results_fine.append({
            "LightGBM": w_lgb,
            "XGBoost": w_xgb,
            "CatBoost": w_cat,
            "ROC-AUC": auc
        })

blend_results_fine = pd.DataFrame(
    blend_results_fine
).sort_values(
    "ROC-AUC",
    ascending=False
).reset_index(drop=True)

print(
    blend_results_fine.head(20).to_string(index=False)
)

 LightGBM  XGBoost  CatBoost  ROC-AUC
     0.62     0.27      0.11 0.965602
     0.62     0.28      0.10 0.965602
     0.63     0.27      0.10 0.965602
     0.61     0.28      0.11 0.965602
     0.61     0.27      0.12 0.965601
     0.63     0.28      0.09 0.965601
     0.63     0.26      0.11 0.965601
     0.62     0.26      0.12 0.965601
     0.61     0.29      0.10 0.965601
     0.64     0.27      0.09 0.965601
     0.62     0.29      0.09 0.965601
     0.64     0.26      0.10 0.965601
     0.60     0.28      0.12 0.965601
     0.60     0.29      0.11 0.965600
     0.64     0.28      0.08 0.965600
     0.61     0.26      0.13 0.965600
     0.63     0.29      0.08 0.965600
     0.63     0.25      0.12 0.965600
     0.60     0.27      0.13 0.965600
     0.64     0.25      0.11 0.965600

In [101]:
best_weights = blend_results_fine.iloc[0]

print("BEST BLEND")
print("=" * 40)
print(f"LightGBM : {best_weights['LightGBM']:.2f}")
print(f"XGBoost  : {best_weights['XGBoost']:.2f}")
print(f"CatBoost : {best_weights['CatBoost']:.2f}")
print(f"ROC-AUC  : {best_weights['ROC-AUC']:.6f}")

BEST BLEND
========================================
LightGBM : 0.62
XGBoost  : 0.27
CatBoost : 0.11
ROC-AUC  : 0.965602

In [102]:
print("Previous best : 0.965597")
print(
    f"New best      : "
    f"{best_weights['ROC-AUC']:.6f}"
)

print(
    f"Improvement   : "
    f"{best_weights['ROC-AUC'] - 0.965597:+.6f}"
)

Previous best : 0.965597
New best      : 0.965602
Improvement   : +0.000005

In [103]:
best_oof_pred_final = (
    0.62 * threshold_oof
    + 0.27 * xgb_oof
    + 0.11 * cat_oof
)

print(
    f"Final OOF ROC-AUC: "
    f"{roc_auc_score(y, best_oof_pred_final):.6f}"
)

Final OOF ROC-AUC: 0.965602

In [104]:
best_test_pred_final = (
    0.62 * threshold_test
    + 0.27 * xgb_test
    + 0.11 * cat_test
)

In [105]:
submission_final = pd.DataFrame({
    "id": test["id"],
    "addicted_label": best_test_pred_final
})

submission_final.to_csv(
    "submission_final_0965602.csv",
    index=False
)

print(submission_final.head())
print()
print("Shape:", submission_final.shape)

       id  addicted_label
0  691369        0.999465
1  691370        0.943620
2  691371        0.928830
3  691372        0.992066
4  691373        0.998041

Shape: (296302, 2)

In [106]:
print(
    "Min:",
    submission_final["addicted_label"].min()
)

print(
    "Max:",
    submission_final["addicted_label"].max()
)

print(
    "Mean:",
    submission_final["addicted_label"].mean()
)

print(
    "Missing:",
    submission_final["addicted_label"].isna().sum()
)

Min: 9.407895820164794e-05
Max: 0.9999998963433037
Mean: 0.710166932384274
Missing: 0